### PR TITLE
Adjust stream network tile rendering

### PR DESCRIPTION
**Pull request by caseypt**
Attempts to satisfy the revisions specified in #1443.

**Testing**
- Open a tab with this branch and another with staging.
- Turn on the stream network overlay.
- Zoom in on each, compare how the streams are rendered, and check that they satisfy the revisions set in #1443.

Connects to #1443

### CODE REVIEW

**Comment by mmcfarland** [comment]
Rendering looks good to me.  Could you update the names from `nhd_streams_v1 | drb_streams_v1` in the tiler and app configs to `***_streams_v2`?  That way we don't have to wait for the cloud front cache to expire before the client can see the changes on staging.

**Comment by caseypt** [comment]
Sure. Will do.

**Comment by caseypt** [comment]
Added a commit to bust the cache.

**Comment by mmcfarland** [comment]
+1

**Pull request merged**
