### PR TITLE
ITSI Speedy Sign Up

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

This aggressively streamlines the ITSI sign-up procedure, by removing all input from the user. We now automatically create an account for the user using information received from ITSI's OAuth end point. If there are any username collisions, we simply add a number to the username, and keep adding it until we get a unique username.

The sign up modal has been considerably simplified, and now serves a purely informational role. The exact wording may be improved. Currently it looks like this:

image

## Demo

mmw-itsi-speedy-sign-up

Connects #950 
Supersedes #951

### CODE REVIEW

**Comment by rajadain** [comment]
Only the last two commits are meaningfully different from #951 and worthy of inspection. I will setup an activity running off my local in ITSI tomorrow where it can be tested.

**Comment by rajadain** [comment]
Ready for testing, just use MMW EXAMPLE 7461A830. Talked to @arobbi7 about the language. Might consider different messaging for embed auto sign-up and non-embed manual sign-up.

**Comment by arobbi7** [comment]
This new workflow makes a lot of sense to me - nice job! I do think it's confusing to be told, within the ITSI embed portal, "When logging in, simply select ITSI." since the only login used to reach that point was the ITSI main login, not anything on MMW. 

For more clarity I think that modal should just read "We've created an account for you using your <name> ITSI account. When logging in to Model My Watershed, simply select ITSI." This message would work in both the embed auto sign-up and the non-embed manual sign up.

**Comment by rajadain** [comment]
I've updated the language to be more generic and removed the username entirely:

image

The reason this was done was because we found users wanting to enter their ITSI credentials in the username / password fields for Model My Watershed. By removing the username from the conversation entirely, we try and make it clearer that users should just press **ITSI** when logging in to Model My Watershed.

**Comment by mmcfarland** [comment]
+1, tested.  Very seamless, I think this is a very nice improvement to the workflow.

**Pull request merged**
