### PR TITLE
Allow display of very large and invalid watersheds

### PR DESCRIPTION
**Pull request by kdeloach**
#### Changes
* Graceful RWD error handling, and better messages
* Display invalid watersheds
* Hide "Analyze" button for invalid watersheds

#### Demo

We now handle errors much more consistently instead of having the UI stuck in a bad state.

image

For invalid (multipolygon) watersheds, we now display a better error message. Since we can't calculate the area, it is hidden in the analyze footer.

image

For valid watersheds that are too large (I have set the limit to 5km^2 for testing purposes) we display the generated watershed along with a warning, and hide the "Analyze" button in the footer.

image

Connects #1657

### CODE REVIEW

**Comment by kdeloach** [comment]
@ajrobbins Feedback on text changes?

For very large watersheds:

image

For multipolygons (analyze endpoints do not support these):

image

**Comment by mmcfarland** [comment]
A bit of duplication in the first and last sentence, maybe combine to:

> Sorry, your Area of Interest is too large to analyze or model.

Then the second sentence as you have it, presently.

I also wonder if we should use the term Area of Interest or "Watershed".

**Comment by kdeloach** [comment]
There may appear to be a lot more changes than necessary, but I encountered several bugs with syncing state between the views and models that have gone unnoticed for some time. I'm looking into ways to reduce the number of changes needed for this feature.

**Comment by ajrobbins** [comment]
If this message is only for RWD, I'd say:

```
Sorry, the watershed you have delineated is too large to analyze or model. xxx km2 were selected, but the maximum supported size is currently yyy km2.
```

Second one looks good!

**Comment by kdeloach** [comment]
> I also wonder if we should use the term Area of Interest or "Watershed".

I think the first error message is used on both RWD and Free Draw mode.

**Comment by ajrobbins** [comment]
>I think the first error message is used on both RWD and Free Draw mode.
If that's the case, I think we should say "the area you have delineated" instead of "Area of Interest" which is not super familiar to people.

**Comment by kdeloach** [comment]
I will remove b7bd983fe4ac4bdc6dd29f91d30dd4ead5c86bbb before merging.

**Comment by kdeloach** [comment]
Updated text and added screenshots.

**Comment by kdeloach** [comment]
Fixing lint and tests now.

**Comment by ajrobbins** [comment]
+1 on the new messages!

**Comment by kdeloach** [comment]
Unit tests pass successfully for me, but fail on Jenkins.

image

**Comment by kdeloach** [comment]
I was able to reproduce these test failures by upgrading my version of Firefox.

**Comment by kdeloach** [comment]
Fixed unit tests.

**Pull request merged**
