### PR TITLE
Feedback icons for geocoded search

### PR DESCRIPTION
**Pull request by rajadain**
**Overview**

 * Add icon UI and configuration for various states of search, including
   default, working, empty (no results), and error.
 * Tease out `message` from model into view, since its purpose is only
   for presentation and not persistence / API access
 * Standardize and consolidate search box state manipulations to a small
   number of `setState____` methods
 * Switch from using `emptyView` and `noResultsTmpl` to just the
   `message` box as defined in `searchTmpl`, according to mockups
 * Style `message` box according to mockups, make dismiss button reset
   search box state and hide `message` box
 * Add `ui-danger` style for errors

**Screencaps**

Searching for location with results:

search-main

Searching for a location without results:

search-empty

Error in search:

search-error

**Testing Instructions**

 * Search for a real location. Click the location. Try selecting a location by pressing Enter while searching.
 * Search for a fake location. Ensure you see the "No results found." message
 * Disconnect internet and search for a location. Ensure you see the "Oops! Something went wrong." message

**Acknowledgements**

Thanks to @ctaylo37 for figuring out the Firefox and Safari issue.

Connects #62

### CODE REVIEW

**Comment by caseypt** [comment]
Nice videos.

**Comment by ctaylo37** [comment]
Yea, do you have a desktop tool to make GIF's quickly?

**Comment by rajadain** [comment]
I used the free and open source [LICEcap](http://www.cockos.com/licecap/), but there's paid tools out there too. http://recordit.co/ is one of the newer ones that automatically uploads to the cloud, but I haven't used it. LICEcap just saves to disk.

**Comment by rajadain** [comment]
Thanks to @ctaylo37 the Firefox and Safari issues are now fixed and this is ready to be tested.

**Comment by caseypt** [comment]
+1. Tested. Looks good. @ctaylo37 has a [different mock up](https://github.com/WikiWatershed/model-my-watershed/issues/62#issuecomment-112083471) for when you click on a result. I assume you guys discussed it, but just want to make sure.

**Comment by rajadain** [comment]
We did discuss it briefly, and it's much simpler for us to re-use the existing animation. I can make it more faithful to the mockup if we strongly desire that.

**Comment by caseypt** [comment]
@rajadain I don't feel strongly either way. Just wanted to check. Thanks.

**Comment by ctaylo37** [comment]
I think it's fine in the search field.

**Comment by kdeloach** [comment]
I don't think it's related to this PR, but I frequently get this error `Uncaught TypeError: Cannot read property 'get' of undefined` at `SuggestionModel.setMapViewToLocation` by typing gibberish in the search field, waiting for some results, then pressing enter.

**Comment by kdeloach** [comment]
Consider dismissing the suggestion dropdown after something is clicked or ENTER is pressed, if possible.

**Comment by kdeloach** [comment]
+ Solid.

**Comment by rajadain** [comment]
@kdeloach The suggestions dropdown is dismissed as soon as the location selected by user click or ENTER is rendered. Would you prefer we dismiss the dropdown as soon as the user clicks or presses ENTER, instead of waiting for the location to load?

**Comment by kdeloach** [comment]
I would say leave as-is for now.

**Pull request merged**
