### PR TITLE
Add Stroud logo to header

### PR DESCRIPTION
**Pull request by caseypt**
## Overview

Per Stroud, their logo is added to the app header. This PR also removes some images that weren't used and adds the source image directory to the asset pipeline. Prior to this PR, we hadn't used any original images in the app.

### Demo

image

## Testing Instructions

- Proceed through the app and verify that the logo is always visible in the header.

Connects #1618

### CODE REVIEW

**Comment by caseypt** [comment]
@jfrankl I had to drop `float: left;` from the header link to get the image to display properly. This didn't appear to cause any problems.

**Comment by arottersman** [comment]
Tested, and the logo is there.

I wonder if it should be clickable like the header label? (although now that I click on the header label, I realize it doesn't do much...)

Also, should we add a `margin-right` on the icon?
screen shot 2016-11-28 at 11 26 29 am

**Comment by jfrankl** [comment]
Thanks for getting the ball rolling. Can you please move the logo to the right side of the bar, next to WikiWatershed? The top left should be reserved for the MMW identity.

image

**Comment by caseypt** [comment]
Pushed a fixup commit to move the logo to the right, link to Stroud's site, and to update the registration page header to have better parity with the app header.

image

image

**Comment by arottersman** [comment]
+1, nice catch on the reset password page!

**Comment by caseypt** [comment]
Thanks!

**Pull request merged**
