### PR TITLE
BiG-CZ: Make HydroShare dates timezone aware

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Some of the dates in the API response were timezone aware, while others were not. Since DATE_MIN was defined without timezone awareness, it could only be compared to similarly naive datetimes.

Using Django's make_aware utility, DATE_MIN is initialized with a timezone. Values coming in from the API are checked for timezone awareness, and are made aware if needed.

This ensures that no information is lost, and comparisons are made between like objects.

Connects #2436 

## Testing Instructions

 * Check out this branch, go to [:8000/?bigcz](http://localhost:8000/?bigcz)
 * Select the Philadelphia HUC-12, search for "water". Ensure results show up and there are no errors.
 * Search for "river". Ensure results show up and there are no errors.
 * Test anything else you can think of.

### CODE REVIEW

**Comment by arottersman** [comment]
Taking a look now.

**Comment by arottersman** [comment]
Able to complete multiple searches, but now using the date filters causes the same naive date error.

**Comment by rajadain** [comment]
oooh good catch, will fix!

**Comment by rajadain** [comment]
Fixup should take care of the filter problems.

**Comment by rajadain** [comment]
Thanks for taking a look! Squashed and rebased on `develop`, merging now.

**Pull request merged**
