### PR TITLE
Modification SVG Fill Patterns

### PR DESCRIPTION
**Pull request by rajadain**
Adds SVG patterns made by @ctaylo37 to the `/model` view. They look like this:

image

Land Cover Thumbnails:

image

Conservation Practice Thumbnails:

image

**Testing Instructions**

 * Draw an area of interest, move on to `/model` view
 * Add a scenario, add various Land Cover and Conservation Practice modifications

**Alternate Scenarios**

 * Try saving modifications and revisit page to ensure they show up correctly

**Notes**

While I'm happy with most of the work done here, the one issue which I need help with is finding the best strategy for pattern loading. Currently it has been added to the end of `base.html`, which means we have an addition of 616 KB to every full page load. Perhaps this is acceptable because all further interaction is done via AJAX calls. Or perhaps we should somehow dynamically load this when people land on the `/model` view, which would make initial load faster, but the transition and loading of this page a little slower. We may even consider adding loading animations to the modification drop-downs until the patterns are loaded.

Another attempt might be to minify `patterns.html`. I've removed all extraneous spacing, but it is still well-indented to be human readable. We could probably save some bandwidth if we got rid of all newlines and whitespace.

Input, there and elsewhere, is welcome.

Connects #257

### CODE REVIEW

**Comment by ctaylo37** [comment]
I think we should definitely minify the HTML file that gets pulled on to the server, but keep a working copy for changes that isn't loaded.

**Comment by rajadain** [comment]
On a side note @ctaylo37, if you'd like to play with the colors / patterns, these are the files you need to adjust: [`patterns.js`](https://github.com/rajadain/model-my-watershed/blob/feature/svg-patterns/src/mmw/js/src/core/patterns.js) for colors, stroke width, opacity etc and [`patterns.html`](https://github.com/rajadain/model-my-watershed/blob/feature/svg-patterns/src/mmw/apps/core/templates/patterns.html) for adjusting the actual patterns. Please note that `patterns.html` has slightly modified `id`s to match what was defined in the app. Based on discussion with @mmcfarland, I imagine these `id`s might change once we have a definitive list, but perhaps that can be a separate PR.

**Comment by caseypt** [comment]
You could try using django `spaceless` template filter in `patterns.html` to reduce the page load: https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#spaceless

**Comment by caseypt** [comment]
+1 Well done. I was able to draw some modifications and see the custom pattern. I saved the project and restored it, and the modifications were redrawn with the correct pattern.

If you can think of a way to test that everything is wired up correctly, consider adding it.

selection_051

**Comment by rajadain** [comment]
@caseypt Good call on removing `randomDrawOpts`. I will make sure it isn't called elsewhere before cleaning up.

Regarding `spaceless`, that's a great find, thank you! But I'm afraid we would transfer the burden of bandwidth to server CPU which must now strip out the spaces for each full page load. What ideally I'd like to do is to treat the `patterns.html` file like a static asset, that can be cached. For example, one idea might be to minify it and put it in the `static` directory, and have the minification be a part of the build step. That way, the space stripping is only happening each time we build the project, instead of each time we serve a page.

Let me start with that, and if there are more ideas of reduction we will incorporate those as well.

This would allow us to use maybe slightly faster serving, but it still wouldn't be cacheable because it won't be an independent request from the browser. A client side delayed load would be ideal, because the user doesn't need the patterns immediately (unless they are landing on a scenario ...), and it would allow the browser to cache the request, or a CDN to quickly supply it, without entanglement with our server side template generation. I'm not sure what is the best way of achieving this, and am open to ideas, as well as thoughts on if it would be worth the effort.

**Comment by caseypt** [comment]
@rajadain Good points. This may be overkill, but we could have a django route that returns the patterns HTML, request it via an AJAX call, [parse it](http://api.jquery.com/jQuery.parseHTML/), then load it into the DOM.

**Comment by mmcfarland** [comment]
I really like the way you laid this out, good stuff.  The 600+kb payload is a little tough to swallow, and I agree with the conversation about it so far.  I think the fills look really good and we should work towards a manageable solution.  Doing a cachable async request is pretty good idea, but I'm curious to see what minified and gzipped payload translates to on production before we try to solve something.  Also a little more concerned with potential parsing time as opposed the xfer time, especially if it ends up being cacheable - would be good to get some numbers to evaluate.  For the time being, so long as it doesn't grind on load for our first milestone, I'm fine with pushing these discussions off to a new issue.

**Comment by rajadain** [comment]
Actually after doing a number of tests, it seems like I was wrong about the 600 KB number. Even though that is the size of the file, what is transferred to the browser is actually under 60 KB, and I'm not exactly sure I understand why that is:

image

One possibility could be the encoding of the characters: the source might be in unicode whereas the browser transfers ASCII. Unsure.

Here's the rough averages I've been able to achieve:

Metric | Without `spaceless` | With `spaceless`
------- | ----------- | -----------
**Time** | 200ms | 210ms
**Size** | 58 KB | 56 KB

So we don't really gain much saving for the additional stripping, thus I've decided to forego the `spaceless` tag for now. I agree with both of you that we should only revisit this if it becomes an issue in the future, rather than overengineering for an unlikely use case now.

**Comment by rajadain** [comment]
I've removed `randomDrawOpts` in the latest commit: https://github.com/WikiWatershed/model-my-watershed/commit/6c2ff6d8703502f9b8ff4f718977af6a69bcd9f6#diff-96ec3a491ec24e06f1414e91dd22d2cbL66

**Comment by mmcfarland** [comment]
I think that small size transfer is the size after getting gzipped from the server, you can have the Network tab report both xfer size and uncompressed size.  I was imagining that an SVG file is mostly made up of repeated characters and would compress very well.  Let's just keep an eye on xfer times and deal with issues that come up.

**Comment by rajadain** [comment]
Added tests to ensure mappings between IDs and patterns is correct, and that draw options are defined for all modifications.

**Comment by rajadain** [comment]
Okay, finalized test additions and fixed a flake8 issue. I've never really written tests before, so would appreciate a quick review to see if they make sense / seem idiomatic.

**Comment by caseypt** [comment]
The tests look good to me. They are a quick way to check that everything is wired up correctly.

**Comment by kdeloach** [comment]
+1 Nice.

**Pull request merged**
