### PR TITLE
Fix precipitation slider input width

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

This PR smooths the precipitation slider input on FF & Safari by giving the whole control a fixed width, which prevents it from resizing dynamically when the numeric value changes.

Connects #2013 

## Testing Instructions

 * get this branch, then `bundle`
 * test the precipitation slider in FF, Chrome, Safari, and IE11 to verify that it still works and is doesn't resize on changes

### CODE REVIEW

**Comment by arottersman** [comment]
Should we make it match the wireframes while we're here?
screen shot 2017-07-10 at 4 40 16 pm

It could alleviate it looking off centered on FF and bizarre in IE11. The styling already exists as `.layerpicker-slider .slider-leaflet`

**Comment by kellyi** [comment]
> Should we make it match the wireframes while we're here?

Question for @ajrobbins ^

**Comment by ajrobbins** [comment]
Yep, let's do it.

**Comment by kellyi** [comment]
Dropped the prior commit and pushed a new one which adds custom style to the precipitation slider:

screen shot 2017-07-11 at 12 51 37 pm

screen shot 2017-07-11 at 12 51 48 pm

I didn't extract the layer selector slider CSS out into a separate file to DRY it out; the browser-specific rules are repeated, so conceivably they could go into a separate file, but the placement rules seem different enough that I think it makes sense to be able to revise the precipitation slider without also dealing with the layer selector slider.

Testing instructions are mostly the same, but it's worth checking out the compare view too now.

**Comment by kellyi** [comment]
On second thought I am going to try to DRY those slider rules a bit.

**Comment by kellyi** [comment]
Ok, moved those rules in 440e969. The project wasn't using `_slider.scss`, so I just removed all of the existing rules there and put the styles for `custom-slider` in there, then adjusted the import and added the class to the precipitation & layer selector slider.

Testing should now also verify that the layer selector slider appearance & functionality's the same as before.

**Comment by rajadain** [comment]
@azavea-bot rebuild

**Comment by rajadain** [comment]
Taking a look now.

**Comment by rajadain** [comment]
The failing check is because of issues on `develop`. This is good to merge.

**Comment by kellyi** [comment]
Thanks for taking a look at this!

**Pull request merged**
