### PR TITLE
Switch API Documentation to DRF-YASG

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

The Django Upgrade in #3123 broken Django Rest Swagger, a project that is no longer maintained. We switch to the recommended (by the author of Django Rest Swagger) alternative drf-yasg for the API generation instead.

This new tool doesn't use the YAML documentation previously there, instead relying on OpenAPI Schema decoration. The documentation is converted to this new format, and some supplemental instruction is added as well.

Connects #3124 

### Demo

Screen Shot 2019-07-30 at 18 30 51-fullpage

## Testing Instructions

* Check out this branch and reprovision your `app` VM to install the new dependencies

      $ vagrant reload --provision app

* Go to [:8000/api/docs](http://localhost:8000/api/docs) and ensure you see the Swagger UI, and not an error page
* Compare the values with production https://modelmywatershed.org/api/docs/ and ensure that the information there has been faithfully captured
* Ensure there are no typos or confusing sentences in the opening instructions near the header

### CODE REVIEW

**Comment by mmcfarland** [comment]
I generated a Token and authorized the docs with `Token XXX-XXX` but I get:

```json
{
  "detail": "CSRF Failed: CSRF token missing or incorrect."
}
```

**Comment by rajadain** [comment]
This is very odd. I was able to reproduce the above error in the morning, but after restarting the VM I can no longer reproduce it. Now, I am able to make API requests without CSRF tokens:

```http
$ echo '{"coordinates":[[[[-75.16468,39.97054],[-75.17086,39.95001],[-75.14888,39.95975],[-75.16468,39.97054]]]],"type":"MultiPolygon"}' | http --print HhBb POST :8000/api/analyze/land/ Accept:application/json Authorization:"Token d0faa35ccd57214e5496f7f50ce1fc4a07c00013"

POST /api/analyze/land/ HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Token d0faa35ccd57214e5496f7f50ce1fc4a07c00013
Connection: keep-alive
Content-Length: 128
Content-Type: application/json
Host: localhost:8000
User-Agent: HTTPie/1.0.2

{
    "coordinates": [
        [
            [
                [
                    -75.16468,
                    39.97054
                ],
                [
                    -75.17086,
                    39.95001
                ],
                [
                    -75.14888,
                    39.95975
                ],
                [
                    -75.16468,
                    39.97054
                ]
            ]
        ]
    ],
    "type": "MultiPolygon"
}

HTTP/1.1 200 OK
Allow: POST, OPTIONS
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Fri, 02 Aug 2019 19:19:07 GMT
Location: /api/jobs/c9643a13-3194-499c-9419-779fccfb58c6/
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding
Vary: Accept, Cookie, Origin

{
    "job": "c9643a13-3194-499c-9419-779fccfb58c6",
    "status": "started"
}
```

Will try a couple of other workflows to see if I can reproduce it again.

**Comment by rajadain** [comment]
According to https://drf-yasg.readthedocs.io/en/1.0.2/readme.html?highlight=csrf#c-swagger-settings-and-redoc-settings, the Swagger UI adds an `X-CSRFToken` header only when `USE_SESSION_AUTH` is enabled. This header is required for CSRF verification. We turned `USE_SESSION_AUTH` off because our API works off Token Authentication, not Session Authentication (which is in place only for the web app, not for API users).

With `USE_SESSION_AUTH` turned on, we do get the `X-CSRFToken` header (and successful requests), but also the Django Login / Logout button:

image

Our options now are:

1. Leave the Django Login / Logout button in the interface enabled
    - Optionally add some text in the intro instructing the user to ignore it
2. Override the core `swagger-ui.html` template in DRF-YASG to try and hide that button, even when `USE_SESSION_AUTH` is turned on https://drf-yasg.readthedocs.io/en/1.0.2/custom_ui.html
3. Add a `@csrf_exempt` decorator to our API views so they can be queried without CSRF protection. They will still need Session / Token Authentication to work, and will still be logged.

I think doing **1** is cheapest, but **3** is most graceful, _if_ we can accept those views not being CSRF protected. Thoughts?

**Comment by mmcfarland** [comment]
I agree with your assessment. Given that we have the CSRF protection currently enabled, it doesn't seem like a great trade-off to lose that in order to get a marginally easier to work with API doc page. I suggest we go with 1 and add some small text to instruct users to it's use (or non-use, as it were), as you suggest.

**Comment by rajadain** [comment]
Alright, ready for another look. Updated the settings and added a line to ignore Django Login in ad1a60f. Also added an empty space at the end of each sentence in the description so adding lines in the future doesn't affect existing ones.

**Comment by rajadain** [comment]
Thanks for the detailed testing! Squashed the fixup. Merging now.

**Pull request merged**
