### PR TITLE
Modify conservation practice colors

### PR DESCRIPTION
**Pull request by caseypt**
* Use colors for the conservation practice tools that may better match
what those practices look like in the real world, without too closely
colliding with colors from the NLCD standard legend.

Connects to #697 

screen shot 2015-08-19 at 4 44 46 pm
screen shot 2015-08-19 at 4 45 01 pm

### CODE REVIEW

**Comment by caseypt** [comment]
Open to suggestions.

**Comment by caseypt** [comment]
Tagging @rajadain as well.

**Comment by rajadain** [comment]
Unsure if there is ever really going to be a satisfactory solution to this, but Cluster Housing is hard to see over Map Box

image

And Porous Paving is hard to see over Google Hybrid

image

One way of solving such a problem is to swap their border colors. This way, both of them have dark and bright colors, one for fill and one for stroke, and will be visible on both dark and light basemaps.

For the record, they're both pretty visible on ESRI World Imagery

image

+1 on the color choices. I really like them and they make a lot of intuitive sense.

**Comment by lliss** [comment]
+1

**Comment by caseypt** [comment]
@rajadain Updated those two practices based on your suggestion.

screen shot 2015-08-21 at 9 50 49 am
screen shot 2015-08-21 at 9 50 55 am
screen shot 2015-08-21 at 9 51 01 am

**Comment by caseypt** [comment]
Also added a commit to make modifying the colors a bit clearer in the future.

**Comment by lliss** [comment]
Failed because of this test:
```
not ok 82 Firefox 39.0 - Modeling modificationConfigUtils #getDrawOpts returns the provided colors
    ---
        message: >
            expected '#888' to equal '#000'
```

**Comment by caseypt** [comment]
@lliss Thanks. Didn't even think to check the tests.

**Comment by rajadain** [comment]
+1 the new colors look good! Tried on all four basemaps, and they are much more accessible.

**Pull request merged**
