### PR TITLE
Add support for Ansible 2.0

### PR DESCRIPTION
**Pull request by hectcastro**
Mostly removing a handful of deprecation warnings and upgrading to versions of Ansible roles that work for Ansible 2.0. The role specification itself has changed from a comma-delimited file to YAML.

An unexpected consequence of the upgrade revealed an issue Packer has with uploading directories that contain symlinks. Previously, roles pulled down by `ansible-galaxy` omitted the `examples` directory that exists within all of our company-wide roles. Now, that directory is included and Packer doesn't like it. Some code was introduced to the Packer driver to remove the directories before Packer runs.

---

**Testing**

Ensure that Ansible 2.0+ is installed on your workstation and provision all of the virtual machines to confirm that the run completes successfully.

### CODE REVIEW

**Comment by mmcfarland** [comment]
On this branch and with ansible 2.0, all but `services` provisions successfully for me.  I get:

```
TASK [azavea.java : Install OpenJDK JRE (headless)] ****************************
fatal: [services]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, 
"failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--
force-confold\"   install 'openjdk-7-jre-headless=7u91-*'' failed: E: Version '7u91-*' for 'openjdk-7-jre-
headless' was not found\n", "stderr": "E: Version '7u91-*' for 'openjdk-7-jre-headless' was not 
found\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state 
information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading
 state information..."]}
```

**Comment by hectcastro** [comment]
Ugh. That's gotta be because I broke the OpenJDK version bump out into a separate PR.

**Comment by mmcfarland** [comment]
Oh, yeah.  I'll just rebase on release and try again.

**Comment by mmcfarland** [comment]
:+1: Post-rebase on `release` provisioned successfully.  All tests pass locally, I think the jenkins result is just a fluke.

**Pull request merged**
