### PR TITLE
Add reset button to Draw

### PR DESCRIPTION
**Pull request by mmcfarland**
* Remove in-progress drawings
* Remove AoI
* Remove Boundary Layer

Connects #294

### CODE REVIEW

**Comment by mmcfarland** [comment]
Would like to point out how small of a change this "trash can" reset feature was to all those PSI veterans out there.  Thanks @kdeloach for the ground work that made this trivial to implement.

**Comment by kdeloach** [comment]
Nice.

**Comment by rajadain** [comment]
+1 works very well. I was able to draw and reset areas of interest using all three methods. Was also able to use reset while drawing. Pressing <kbd>Escape</kbd> while drawing also works, I can't remember if it worked earlier or not. Resetting hides the AoI bar at the bottom. Drawing a new shape without resetting also hides the AoI bar. I also started with a saved shape, went all the way back to draw view and drew a new shape.

It may be nice to make the AoI bar transition away instead of just vanishing, but that can be a part of a UI polish effort in the future.

I'm not a big fan of adding `!important` declarations to CSS, but in this case I couldn't see a quick way around it. We may have to refactor the styling of all those buttons to accommodate this.

**Comment by caseypt** [comment]
Consider adding a test for `ResetDrawView.reset`

**Comment by mmcfarland** [comment]
@caseypt 46dc47b added with new tests.

**Comment by mmcfarland** [comment]
@azavea-bot rebuild

**Comment by caseypt** [comment]
Looks good. Tests pass for me.

**Pull request merged**
