### PR TITLE
Add custom icons to layerpicker

### PR DESCRIPTION
**Pull request by arottersman**
## Overview

Adds @jfrankl's new custom icons to the layerpicker.

They are included via `fontello` and added as a sibling to the existing font-awesome assets.

Connects #1722 

### Demo

screen shot 2017-03-06 at 2 56 26 pm

## Testing Instructions

 * `./scripts/bundle.sh --vendor`
* `./scripts/bundle.sh`

Confirm the icons show up and there are no console errors.

### CODE REVIEW

**Comment by jfrankl** [comment]
This looks good to me!

@arottersman and @ajrobbins I am wondering about the order of the layer groups. Basemaps doesn't strike me as the most important one. Should we pick another category for the first and therefore default spot?

**Comment by ajrobbins** [comment]
I think the order, left to right, should be: Streams, Coverage, boundaries, observations, basemaps.

**Comment by arottersman** [comment]
Bold. I'll add a commit.

**Comment by arottersman** [comment]
screen shot 2017-03-07 at 1 31 50 pm

**Comment by arottersman** [comment]
Thanks. I'll keep myself prepared.

**Comment by arottersman** [comment]
Uch, build is failing because I wrote a test that was counting on the basemaps being the first in the layerpicker.

**Comment by arottersman** [comment]
@mmcfarland Is this okay to merge?

**Comment by mmcfarland** [comment]
Can you add a `title` tag to each of the icons?  It's a little difficult to guess what they might be, a tooltip would help.

**Comment by arottersman** [comment]
Good idea
gys5giyxeg

**Comment by mmcfarland** [comment]
+1, thanks!

**Pull request merged**
