### PR TITLE
Add modal to resend activation

### PR DESCRIPTION
**Pull request by lewfish**
To test:
 * Create a new account, but don't activate.
 * Click Send Activation Email (located between 'Forgot?' and 'Sign Up' on the Login modal)
 * Enter the email for the account just created. It should send an email (on the console in development mode).
 * Try triggering various error messages. Make sure the enter button works in addition to clicking the button.
   * Try entering a non-email address string.
   * Try entering a valid email address that is not associated with a user.
   * Try entering an email address for a user who has already activated their account.

This was pretty easy thanks to the refactoring done by @rajadain 

Connects #361

### CODE REVIEW

**Comment by lewfish** [comment]
@azaveaci rebuild

**Comment by rajadain** [comment]
It seems like there's a missing file in the commit: `user/templates/resendModal.html` referenced in `user/views.js`. Running `./scripts/bundle.sh` gives the following error:

```
Error: Cannot find module './templates/resendModal.html' from '/opt/app/js/src/user'
    at /opt/app/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/opt/app/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/opt/app/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /opt/app/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by lewfish** [comment]
You're right. I just added the missing file.

**Comment by rajadain** [comment]
I'm unsure if the "Send Activation Email" button should always be visible. How about making it visible only when login fails due to the account not being activated?

image

**Comment by rajadain** [comment]
Since the ultimate goal of this user interaction is to log in, we should always redirect the user back to the Login modal, instead of letting them continue as guest:

image

**Comment by rajadain** [comment]
+1 tested, works as advertised, great job. Very clean code! Apart from the two comments above I'm very happy with this.

**Comment by lewfish** [comment]
I kind of agree with about only showing the "Send Activation Email" if the user logs in unsuccessfully to avoid cluttering the modal, but what if the user realizes they forgot to activate, and don't realize they can get to the button by logging in unsuccessfully? @mmcfarland What do you think?

**Comment by rajadain** [comment]
I guess what I'm thinking is: How will a user realize they forgot to activate? Either when they see the email, from where they can click the activation link directly, or if they try to login and it tells them that they haven't activated yet (and also shows them the button to resend activation email).

**Comment by rajadain** [comment]
But my concern is not cluttering the modal: I think it looks pretty fine where it is. It just doesn't feel like it fits with every other user action at that time. I also wonder if it could be a security issue.

But I don't feel very strongly about it, so we can also just leave it there.

**Pull request merged**
