### PR TITLE
Fix Runoff colors, labels

### PR DESCRIPTION
**Pull request by rajadain**
Change colors and labels to match the values in the micro site:

image

Connects #695 
Connects #549

### CODE REVIEW

**Comment by lewfish** [comment]
The water quality stacked bar chart in the compare view needs to be changed as well. You'll have to find a fourth color that looks good with those three.

**Comment by rajadain** [comment]
I've left that chart as it is right now, since they represent different values, and adds to the visible differentiation:

image

But I can make them the same colors if that is deemed appropriate.

**Comment by jamesmcclain** [comment]
+ 1 Tested.

Just out of curiosity, where did this color scheme come from?

**Comment by rajadain** [comment]
@jamesmcclain I took the colors from the Micro Site, which I think was designed by @ctaylo37.

**Comment by jamesmcclain** [comment]
Autumn colors

**Pull request merged**
