### PR TITLE
Move Feature Controls

### PR DESCRIPTION
**Pull request by mmcfarland**
* Move the controls to the top so they aren't obscured by footer elements
* Apply styling and classes to make the tools consistent with the existing leaflet controls

Connects #806

### CODE REVIEW

**Comment by caseypt** [comment]
I'm seeing boxes under the button and control containers when the containers are expanded. I checked that I have the latest SASS loaded:

screen shot 2015-09-17 at 4 35 56 pm

**Comment by mmcfarland** [comment]
Box Shadow fixed in f9eb974

**Comment by caseypt** [comment]
:+1: 

screen shot 2015-09-17 at 4 50 21 pm

**Comment by mmcfarland** [comment]
@azavea-bot rebuild

**Pull request merged**
