### PR TITLE
Activate tooltips on click instead of hover

### PR DESCRIPTION
**Pull request by caseycesari**
## Overview

Tooltips are now activated on click instead of hover so that links in the tooltip text are now clickable. Previously, the tooltip closed as the pointer was moved from the tooltip icon to the tooltip text, preventing the user from clicking on any links in the text.

To better unify the UI/UX of the app, the tooltips in the legend were updated to behave in the same way. Additionally, the style of both tooltips was made consistent.

Links were added to the RWD tools. Also, a general link to documentation about the various draw tools was added to the sidebar instead of each draw tooltip (as previously requested). This seemed like a more appropriate solution now that there is a space for explanatory text near the tools.

Connects to #1749
Connects to #1233 

### Demo

mmw7

## Testing Instructions

- View the tooltips for various draw tools, and verify that they open on click and not hover.
- Try to click the links in the RWD tooltips.
- Verify the legend tooltips behave in the same way as the draw tool tooltips.

### CODE REVIEW

**Comment by rajadain** [comment]
Currently the user has to click outside the popup to make it disappear. This can sometimes be tricky, because a user may accidentally click an active element (on the map, a button, or an accordion header) that affects the UI inadvertently.

How difficult would it be to close the popup on re-clicking the help icon (in addition to, rather than instead of, the current behavior)? I suppose there will need to be some way of tracking state, which could get messy, but perhaps not since the each popup parent has a reference to its popup with state.

**Comment by ajrobbins** [comment]
What about putting an X in the popup to close? I think from a user perspective clicking outside of the popup to close it is also expected, but it would be helpful to have an explicit close button too.

**Comment by rajadain** [comment]
Just did a quick read of [bootstrap popover](http://getbootstrap.com/javascript/#popovers), doesn't seem like either case is natively supported. Between static and dismissable popups, I like the dismissable ones (that are currently being used here) better. There's a slightly ugly hack here http://stackoverflow.com/a/13413660/6995854 which I'm not sure will work, but might be worth a shot.

**Comment by caseycesari** [comment]
Adding the close button would be a bit of a hack, but requiring that users click the help icon again to close it is built in to Bootstrap and would be easy to implement. See the example here: http://getbootstrap.com/javascript/#live-demo-1

**Comment by caseycesari** [comment]
One downside of only using the help icon to open and close the tooltip is that it's then possible to open multiple tooltips at once:

screen shot 2017-04-06 at 12 08 30 pm

**Comment by rajadain** [comment]
I'd be okay with keeping it as it is for now, and making another card to enhance popups with a close button.

**Comment by caseycesari** [comment]
Created an issues for follow-up since any of the suggested changes will require some work: https://github.com/WikiWatershed/model-my-watershed/issues/1793

**Pull request merged**
