### PR TITLE
Display current lat lng on map

### PR DESCRIPTION
**Pull request by kdeloach**
This adds a control in the corner of the map to display the current lat lng for debugging purposes. Clicking on the map will also log the current lat lng in the console.

image

Connects #1662

### CODE REVIEW

**Comment by kdeloach** [comment]
@mmcfarland @ajrobbins @jfrankl :+1:  / :-1: ?

**Comment by ajrobbins** [comment]
To clarify: this only happens when a point is selected for RWD, right? It seems really useful for debugging on staging, but I'm not sure it should end up on production.

**Comment by kdeloach** [comment]
Right now it's always on. I could update it to only show while dragging a marker (in draw mode). Or only enable it in debug mode (staging).

**Comment by ajrobbins** [comment]
I meant, that is is the lat/lon of the clicked RWD point, right? It doesn't show when you draw a shape or select by boundary, right?

**Comment by kdeloach** [comment]
Demo: http://algiers:8000/

**Comment by ajrobbins** [comment]
I see! I was misunderstanding. I think this should be for staging only. It would be helpful for debugging, but kind of distracting in production. @mmcfarland ?

**Comment by mmcfarland** [comment]
Rather than wire it into an environment, let's add this now for debugging and revert the commit when we're done having external folks debug.

**Pull request merged**
