### PR TITLE
Upgrade Leaflet Draw to 0.3.0

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Improves touch behavior on Windows touchscreens in Edge and Internet Explorer 11. Chrome still has issues when using the mouse, and Firefox when using the touchscreen.

## Testing Instructions

Test drawing a shape on various browsers on a Windows touchscreen device, using both the mouse and touchscreen.

Connects #649

### CODE REVIEW

**Comment by mmcfarland** [comment]
> Chrome still has issues when using the mouse, and Firefox when using the touchscreen.

Sounds like we at least have a workaround for those browsers.  We should recommend Chrome-> touch; FF -> mouse ?

**Comment by rajadain** [comment]
Yes, but I think that was already working. What is most worrisome are the systems described in #649, where the user's computer seems to have enough touch support to mess up Chrome, but not enough for them to actually use their fingers.

**Comment by rajadain** [comment]
Testing on a Windows Touch device, it is clear that Edge works correctly in both cases. And even Firefox works correctly in both cases. It's just that the vertex boxes are much smaller in Firefox than they are in Edge and Chrome, which makes it a harder target to hit with a finger. Somehow Edge and Chrome can detect if the device is a touch screen and make the vertex boxes bigger. If one is careful and intentional in Firefox, one can use both mouse and touch correctly.

So this only leaves mouse misbehavior in Chrome. I'm going to give this a quick shot and see if we can fix it ourselves.

**Comment by rajadain** [comment]
This work has brought us 80% of the way there, with the only missing use case being Chrome on Windows. I say we merge this, and point #1190 in the next sprint for investigating that specific case.

**Pull request merged**
