### PR TITLE
Unquote arrays to fix test

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

The quotes were causing some tests to fail in Chrome and Safari, since the value `"[]"` would be parsed as a string not an array, but not in Firefox which automatically casted the string to an empty array.

## Testing Instructions

Run `./scripts/testem.sh` in Chrome and Firefox, ensure that all tests pass.

Connects #705

### CODE REVIEW

**Comment by caseypt** [comment]
Were you seeing consistent failures for these tests? I've run them a couple times, and haven't seem them fail at all.

**Comment by caseypt** [comment]
In any case, all the tests pass on this branch for me in Firefox, Chrome, Safari, and from the command line. +1

**Comment by rajadain** [comment]
Yes on `develop` I'm still seeing it:

image

image

On Chrome for Mac 44.0.2403.155 (64-bit)

**Comment by caseypt** [comment]
Same version here. Weird.

**Pull request merged**
