### PR TITLE
Monitor: Modeling Stage Interaction

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Adds Monitor tab to the switcher in the Modeling stage, and reuses the data catalog views to allow searching for data. Edits views to ensure they fit, and changes behavior to ensure search state from the Analyze stage carries over correctly.

Connects #2621 

### Demo

* Overall (the colors are a little off in this gif):

    

* Modeling Stage

    screen shot 2018-02-22 at 10 38 17 am

* Monitor Tab

    screen shot 2018-02-22 at 10 38 25 am

* Filter Sidebar

    screen shot 2018-02-22 at 10 38 42 am

* Search Detail

    screen shot 2018-02-22 at 10 38 50 am

* Analyze Tab

    screen shot 2018-02-22 at 10 39 29 am

Also tagging @ajrobbins and @jfrankl for visual review.

## Testing Instructions

* Check out this branch and `bundle`
* Go to [8000/](http://localhost:8000/) and select an area. Proceed to Analyze. Proceed to Modeling.
* Ensure you see the Monitor tab in the switcher above. Ensure clicking the three buttons changes the tabs correctly.
* Search for something in Monitor tab. Ensure switching to Analyze or Model hides Monitor map elements correctly, and restores them correctly on returning.
* Open the Filter Sidebar and ensure it looks okay (no overlaps or style issues) and works correctly. Opening a detail result, or switching to Analyze or Model, should close the Filter Sidebar. It will not open automatically on returning.
* Ensure that when you click "New Project", select another shape, and proceed to Analyze, the results in Monitor are cleared correctly.
* Search for something in Monitor in the Analyze stage and proceed to Modeling stage. Ensure that the Monitor tab state is preserved. The search form, filters, search results, catalog selection, and detail selection should be the same as before Modeling stage. Scroll position will not be preserved.
* Refresh a saved project and ensure Monitor works just as well as it does when entering via Analyze.

### CODE REVIEW

**Comment by arottersman** [comment]
Taking a look!

**Comment by arottersman** [comment]
TR-55 BMPs aren't cleared when switching to Monitor, and this prevents clicking Monitor shapes on the map. We may want to re-order the layers or not show the BMPs.

screen shot 2018-02-22 at 11 47 27 am


screen shot 2018-02-22 at 11 47 46 am

**Comment by ajrobbins** [comment]
+1 visually!

**Comment by rajadain** [comment]
Thanks for the review! That's a great catch. I looked into it a little bit, but think it's a larger refactor than can be snuck in here, since the polygons are added raw, not to a specific layer which can be easily hidden and shown. I'll make a follow up card for that. Going to merge this in for now.

**Comment by rajadain** [comment]
Made #2676 for that.

**Pull request merged**
