### PR TITLE
BiG-CZ: Branding Changes

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Update text in the splash page and the analyze page. Add more sponsor logos in the splash page. Move sponsor logos below main call to action in splash page. Update favicon.

Also tagging @ajrobbins for visual review.

Connects #2394 

##### Splash Page

image

##### Draw Page

image

##### Analyze Page

image

##### Data Page

image

##### Splash Page

image

##### Draw Page

image

##### Analyze Page

image

## Testing Instructions

 * Check out this branch and run `manage.sh collectstatic` and `bundle.sh --debug --vendor`
 * Go to [:8000/?bigcz](http://localhost:8000/?bigcz) and ensure you see BiG-CZ specific text and branding
 * Go to [:8000/](http://localhost:8000/) and ensure you see WikiWatershed specific text and branding
 * Use [this document](https://docs.google.com/document/d/1oaS6YidSgJPsREBQcGgh70Q__aj56lBMQE4i5GbbdBU/edit#) rather than the issue description as reference for checking

### CODE REVIEW

**Comment by ajrobbins** [comment]
Looking so good! Notes:
- on Splash page, the BiG CZ logo should be separated from the "supported by" logos - BiG CZ is the product, which is supported by NSF, Stroud, and WPF
- Can you post a screenshot/confirm that for BiG CZ, on the "search data" page, the page title is now "Datasets"? (doc item 4)

**Comment by aufdenkampe** [comment]
This is looking good.

Analogous to https://github.com/WikiWatershed/model-my-watershed/pull/2476#issuecomment-341771602:
* on Splash page for MMW, the WikiWatershed logo should be separated from the "supported by" logos - WikiWatershed is the product/project, which is supported by Stroud, WPF and NSF (in that order).

Note: we'll add other logos for minor supporters for an upcoming release. Those other supporters for WikiWatershed are all listed at the bottom of the left column here: https://wikiwatershed.org/about/. In addition to above, they include:
* Virginia Wellington Cabot Foundation
* The Dansko® Foundation
* Generous donations from Peter Kjellerup and Mandy Cabot
These were early seed funders, but I don't have logos for them. @ajrobbins, could you create another issue for those?

Thanks!

**Comment by rajadain** [comment]
### Splash Pages

#### BiG-CZ

image

#### MMW

image

### Data Page

image

Also updated the screenshots in the description.

**Comment by rajadain** [comment]
Also tagging @jfrankl for feedback on the splash pages above.

**Comment by aufdenkampe** [comment]
Looking good!

Two more tweaks:
* on the Datasets page for BiG CZ, can you change the tab for "WDC" to "CUAHSI WDC", as described in #2470?
* for the MMW Splash page, would it be possible to add logos for WPF, NSF under the "Supported by:" list, in that order and ahead of the Stroud logo?

Thanks!

**Comment by rajadain** [comment]
MMW Splash Page Updated (also in the description above):

image

The "CUAHSI WDC" and other changes are covered in #2474.

**Comment by aufdenkampe** [comment]
Awesome! Thanks.

**Comment by arottersman** [comment]
Taking a look now

**Comment by rajadain** [comment]
Thank you everyone for the review!

**Comment by emiliom** [comment]
Sorry for the late comment (though the PR is not merged yet) ...

In the **BiGCZ / Draw Page** screenshot, the text under Select Area doesn't say anything about the AOI limit (1,500 km2). Now, I didn't review @aufdenkampe's "branding text" Google Doc, but the plan was that the AOI would be shown there explicitly and prominently.

On that same page, I'll note that the text says "Explore mapped layers, such as streams, land cover, soils, boundaries ...", which does not include anything about the dataset search capability or WDC data exploration. So it's a bit misleading.

**Comment by rajadain** [comment]
Ah good catch, and not a minute too soon. Any recommendations @aufdenkampe?

**Comment by emiliom** [comment]
Thanks @rajadain. Since it's close to the end of the day for you and Anthony (but not me!), I've gone ahead and provided my [suggested changes on the Google Doc mockup](https://docs.google.com/document/d/1oaS6YidSgJPsREBQcGgh70Q__aj56lBMQE4i5GbbdBU/edit#). My changes only involve the second paragraph, and I used "Suggesting" mode to make the changes stand out clearly.

**Comment by rajadain** [comment]
Thanks @emiliom. There's no rush on getting this out today, can wait till Monday morning as well. I'll await more feedback before adding the final copy.

**Comment by emiliom** [comment]
Ok. But I am done commenting. 

Thanks for all the hard work on this last batch of changes! Looking great.

**Comment by aufdenkampe** [comment]
I like Emilio's suggested edits to the text on the Select Area page. Please include them in the release.

**Comment by rajadain** [comment]
Updated Draw Page text:

image

Merging this shortly.

Thanks for all the input!

**Comment by aufdenkampe** [comment]
Looks good, except for the typo in "visualize" in the second paragraph.

**Comment by rajadain** [comment]
Whoops sorry about that. Fixed below:

image

**Pull request merged**
