### PR TITLE
Add DRWI Perimeter, limit Recent Weather to it

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Adds a DRWI Simple Perimeter boundary, and limits Recent Weather to it. Recent Weather is only available for 11 stations, but is needed for areas slightly beyond the DRB. This is shown in QGIS:

image

where the red dots are the Recent Weather data stations, the dark pink is the DRB, and the light pink is the additional area covered under DRWI. The yellow is the buffered simplified boundary we use to check if an area of interest is within the DRWI or not.

See commit messages for details.

Connects #3547

### Demo

image

## Testing Instructions

* Check out this branch and `bundle.sh --debug`
* Go to http://localhost:8000 and log in (since weather simulations can only be loaded for logged in users)
* Pick a shape within the DRB (e.g. City of Philadelphia-Schuylkill River HUC-12)
* Model it with Watershed Multi-Year Model
* Add Changes to make a new scenario
* Click Weather Data to load the weather modal
* Open the Available Data dropdown
  - [x] Ensure that NASA NLDAS 2000-2019 is available
  - [x] Ensure that RCP 4.5 and RCP 8.5 are available
* Pick a shape outside the DRB but within the DRWI, e.g. Landing Creek HUC-12
* Repeat the above steps to get to the Available Data dropdown
  - [x] Ensure that NASA NLDAS 2000-2019 is available
  - [x] Ensure that RCP 4.5 and RCP 8.5 are not available
* Pick a shape outside the DRWI, e.g. Elklick Creek HUC-12
* Repeat the above steps to get to the Available Data dropdown
  - [x] Ensure that NASA NLDAS 2000-2019 is not available
  - [x] Ensure that RCP 4.5 and RCP 8.5 are not available

### CODE REVIEW

**Review by emilyhu0106 — COMMENTED** [review]
I tested the weather data in HUCs at different areas, and it works as instructed. Nice work!

I tried two different HUC-12s in DRWI and DRB (City of Philadelphia-Schuylkill River HUC-12 and Darby Creek HUC-12), I can see all the weather options, but strangely there's no differences among the scenarios with different weather data. 
image

I'm curious if you see this at your end as well and if the weather data are same among the options inside DRB.

**Comment by rajadain** [comment]
I just tried this with Darby Creek (on staging, since I had manually deployed this there for our clients as well) and am seeing marked differences:

image

Let's pair on this today to figure out what's wrong.

**Review by emilyhu0106 — APPROVED** [review]
After pairing, we realized that the inconsistency in the weather modeling result is related to exit the modal before the modeling finishes. I created a separate issue #3550 to address this.

This card did well for adding the DRWI shape to limit recent weather.

**Comment by rajadain** [comment]
Thanks for the thorough review, and for making the follow up card!

**Pull request merged**
