### PR TITLE
Style WDC detail view

### PR DESCRIPTION
**Pull request by jfrankl**
## Overview

Style detail view for WDC.

### Demo

image

## Testing Instructions

 * Look at the detail view for a dataset in the WDC catalog

### CODE REVIEW

**Comment by rajadain** [comment]
CINERGI and Hydroshare detail views should also be updated. The small × button looks odd, and is hard to click:

image

Their templates are [`resultDetailsCinergi`](https://github.com/WikiWatershed/model-my-watershed/blob/release/1.20.0/src/mmw/js/src/data_catalog/templates/resultDetailsCinergi.html) and [`resultDetailsHydroshare`](https://github.com/WikiWatershed/model-my-watershed/blob/release/1.20.0/src/mmw/js/src/data_catalog/templates/resultDetailsHydroshare.html)

**Comment by jfrankl** [comment]
@rajadain could you please take another look?

**Comment by ajrobbins** [comment]
Jeff suggested a treatment for the catalog name here https://github.com/WikiWatershed/model-my-watershed/issues/2295

**Comment by rajadain** [comment]
Added in e996ee1

image

**Pull request merged**
