### PR TITLE
Add CORS Support to Geoprocessing API

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Add [CORS support plugin](https://github.com/ottoyiu/django-cors-headers) and allow all hosts to access the API.
We may restrict this in the future.

Connects #2452

### Demo

image

## Testing Instructions

 * Check out this branch and reprovision `app`
 * Go to [:8000/](http://localhost:8000/) and open the Network panel of Developer Tools
 * Draw / select a shape and proceed to Analyze. Watch the network requests for analyze submissions.
 * Inspect any such request. The response headers should include

       Access-Control-Allow-Origin: *

### CODE REVIEW

**Comment by arottersman** [comment]
I think we should restrict this to only apply to the `/api` endpoints.

**Comment by rajadain** [comment]
Added the URL regex in d501570. I don't think we need to add it to the `/mmw/` endpoints because they're not for public consumption anyway?

**Comment by arottersman** [comment]
>  I don't think we need to add it to the /mmw/ endpoints because they're not for public consumption anyway?

That's right

**Comment by rajadain** [comment]
Squashing and merging now. Thanks for taking a look!

**Pull request merged**
