### PR TITLE
Analyze Sidebar

### PR DESCRIPTION
**Pull request by caseypt**
Adds back the analyze page and implements the sidebar design. See commit messages for details.

**Testing instructions**
- Select an AoI.
- You should advance to the analyze page which is sporting the new sidebar design.
- Advance to the modeling page. The modeling tab should be active and the analyze results shouldn't need to be fetched.

screen shot 2016-02-09 at 12 00 58 pm

TODO: 

- [x] Add a new view that wraps the analyze view, similar to the one used in modeling. This will only show an Analyze tab.
- [x] Apply new map sizing for sidebar but no header.
- [x] Advance to modeling page.
- [x] Preserve analyze results from analyze to modeling.
- [x] Review changes from initial PR and bring back any code that may now be needed again.

Connects to #1134

### CODE REVIEW

**Comment by caseypt** [comment]
Adding @jfrankl so he can get a look at the "Model this area" button. See the above screenshot.

**Comment by mmcfarland** [comment]
A workflow issue is that you can't now go back from Analyze to Draw, or otherwise reset your AoI.  Not sure where the most appropriate spot for that button would be.  Maybe a floating "Reset" button the map, similar to the one in draw tools?

Additionally, you should try rebasing current release to see if the new collapse/toggle button interferes with the new Model button

**Comment by mmcfarland** [comment]
Code looks good.

**Comment by mmcfarland** [comment]
+1

**Pull request merged**
