### PR TITLE
Monitor: Add BiG-CZ Search

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Adds the BiG-CZ search functionality to the Monitor tab, and styles it according to the mockups. Harmonizes behavior with rest of MMW, so that switching between Analyze and Monitor, going from Analyze / Monitor to Draw, and to Model, behaves as expected.

The Model stage currently does not have the Monitor tab. That will be added in #2621.

These upgrades break BiG-CZ. That will be fixed in #2639.

Connects #2622 

### Demo

* Overview

    

* Analyze Tab

    screen shot 2018-02-15 at 9 45 04 am

* Monitor Tab (with search results)

    screen shot 2018-02-15 at 9 45 09 am

* Monitor Tab (with filter sidebar)

    screen shot 2018-02-15 at 9 45 14 am

* Monitor Tab (with detail view)

    screen shot 2018-02-15 at 9 45 24 am
    screen shot 2018-02-15 at 9 46 02 am

Tagging @ajrobbins and @jfrankl for visual review.

### Notes

The screen capture software I use slows down the browser. In reality the interactions are faster than the ones seen above.

There were no mockups for the filter sidebar, so I made it fit as best as I could, but we may need to create a follow up card for design tweaks there.

Should there be a spinner under the Analyze and Monitor tab headers when they are loading?

## Testing Instructions

* Check out this branch and `bundle`
* Go to [:8000/](http://localhost:8000/) and select / draw a shape
* See the Monitor tab in the Analyze stage. Click it and search for something. Ensure the search works as expected.
* Test the filters. Ensure they work as expected.
* Ensure items on the map are in sync with those in the sidebar.
* Click an item in the sidebar. Ensure the details view is shown, and the map only shows that items shape, and you can scroll the details view if it is too long.
* Ensure pagination works as expected.
* Ensure switching to Analyze hides the Monitor results from the map.
* Ensure switching back to Monitor restores the results on the map.
* Ensure tab state (which analyses is selected, which catalog is selected, which result is selected, scroll state) remains consistent when switching between Analyze and Monitor.
* Ensure that any Monitor specific elements (map popup when multiple results, filter sidebar) are removed when switching to Analyze.
* Ensure that clicking "Change Area" behaves as expected, and when revisiting Monitor you get a blank slate for a new search.
* Ensure that selecting a model and moving on to Model removes the Monitor elements from the map.
* Ensure that when selecting "New Project" from the Model and going back to Monitor, you get a blank slate for a new search.
* Ensure that selecting "New Project" from the Projects list and going back to Monitor, you get a blank slate for a new search.
* Ensure the visual look and feel matches and feels harmonious, and follows [the mockups here](https://app.goabstract.com/projects/76ed1390-dea8-11e7-a27c-0f868efbc56f/branches/714a77e0-fa21-11e7-835a-4527db42429f/files/7F4A25A6-1E0D-48A0-B999-8629B42E4E23/pages/6F1410C0-7988-41C6-849F-1AAB98853CD7?changed=true)

### CODE REVIEW

**Comment by arottersman** [comment]
Taking a look now!

**Comment by arottersman** [comment]
Overall, looks great! Noticed two bugs:

1. If you open a popup on CUAHSI WDC, then switch to "Analyze" the CUAHSI result will remain on the map.

screen shot 2018-02-19 at 12 25 57 pm


2. IE11 is missing the catalog tabs
screen shot 2018-02-19 at 12 28 04 pm

**Comment by jfrankl** [comment]
Looking good! Here are two modifications:

1. Please add a vertical border between the sidebar and the filter:

image

2. Make sure the heading "Filter" and the filters are aligned (see red dotted line for reference, but don't reproduce red line in application)

image

**Comment by rajadain** [comment]
Filter sidebar styling adjusted accordingly (b006da0 and b229a94)

image

Popup now disappearing properly (26de679):

**Comment by rajadain** [comment]
Still working on the IE issue.

**Comment by rajadain** [comment]
Added a fix for the missing tab panel headers in IE11:



This also fixes the search form width which was narrower than other browsers. Tested all other browsers to ensure that they remained unaffected.

This is ready for another review.

**Comment by rajadain** [comment]
Thanks for the thorough review! Squashed fixups, will merge once green.

**Pull request merged**
