### PR TITLE
Bake CSRF token in all ajax requests

### PR DESCRIPTION
**Pull request by kdeloach**
Extends jQuery ajax options to include the `X-CSRFToken` header in each
ajax request.

Connects #197

### CODE REVIEW

**Comment by mmcfarland** [comment]
Does this behave well in the case of a non-authenticated user visiting the site and not having this cookie value available?

**Comment by kdeloach** [comment]
Good point. We should test that this allows authenticated and non-authenticated users to queue jobs.

**Comment by rajadain** [comment]
Consider adding `$.ajaxSetup()` to the new `csrf` helper file, so that for any module that needs it can simply `require` it and not have to also initialize it. Is there a use case where we require it but don't initialize it?

**Comment by kdeloach** [comment]
The CSRF token actually changes after logging in. Since a page refresh doesn't happen, we need to update the CSRF token attached to all ajax requests. Requiring the csrf module a second time would have no effect.

**Comment by rajadain** [comment]
If we moved this line:

```
var csrftoken = getCookie('csrftoken');
```

into the `beforeSend` function, it would always get the current CSRF token, and then requiring `csrf` would be enough.

**Comment by kdeloach** [comment]
Great suggestion, will update.

**Comment by rajadain** [comment]
Tested with both logged in and not logged in users. GET requests consistently don't get CSRF token headers and still work in both cases, and POST requests consistently get CSRF token headers and also work correctly in both cases.

It should be noted that CSRF Tokens are available for all users, and are not a function of a users authentication status. They do not verify if a user is logged in, but instead that the JavaScript request is coming from a page that the served, and is not being surreptitiously accessed by a third party. They prevent Cross Site Request Forgery.

Logged in users have a `sessionid` cookie set. The `csrftoken` cookie is set for all users.

Consider deleting the `helpers.js` file since this subsumes it.

**Comment by rajadain** [comment]
Can we further reduce redundancy by requiring this in some universal dependency like the `shim/backbone.js` so that we don't have to `require` it in all modules? Once the behavior of `$.ajaxSetup` is defined it should just apply to all `$.ajax()` calls after it, right?

**Comment by kdeloach** [comment]
Updated based on your suggestions.

Since main.js is the entry point to this application, attaching the csrf ajax options there makes the most sense to me. Note that this is a universal change that affects all ajax calls throughout the app.

**Comment by rajadain** [comment]
:+1: looks really great! I've noted your comment about rebasing #216 on top of this, will edit the content there to work with this.

**Pull request merged**
