### PR TITLE
Add table for GWLF-E quality results

### PR DESCRIPTION
**Pull request by lewfish**
Add tables for GWLF-E quality results.

To test, `cd src/mmw/requirements/src/gwlf-e/` and then check out the branch from https://github.com/WikiWatershed/gwlf-e/pull/50 to get the latest GWLF-E code that computes quality results, and then run `debugcelery.sh` and `debugserver.sh`.

screen shot 2016-05-19 at 10 42 51 am 2
screen shot 2016-05-19 at 10 42 54 am 2

Connects #1270

### CODE REVIEW

**Comment by mmcfarland** [comment]
Let's add units to the headers, which is `kg` in all cases.  Maybe append "(kg)" to the header?

**Comment by mmcfarland** [comment]
I agree with your suggestion, I think `Total Loads`, `Loading Rates`, `MAC` and `MLFC` should be in a separate table, immediately below. Additionally, the following two keys should be added above the original table:  `MeanFlow` and `MeanFlowPerSecond`

**Comment by mmcfarland** [comment]
Also, the numerical columns should be right-justified like the other tables.

**Comment by mmcfarland** [comment]
Sorry, should have mentioned the units for the mean flow lines are:  MF: m<sup>3</sup>/year, MFS: m<sup>3</sup>/s

**Comment by lewfish** [comment]
Updated according to feedback.

**Comment by kdeloach** [comment]
I merged https://github.com/WikiWatershed/gwlf-e/pull/50.

**Comment by mmcfarland** [comment]
+ 1 We'll probably need a style pass, but this looks good.  One last output modification, can you have a minimum 2 decimial places for whole numbers, so they line up when sorted?

screenshot from 2016-05-19 11 44 37

**Comment by kdeloach** [comment]
+1 Cool

**Comment by lewfish** [comment]
> One last output modification, can you have a minimum 2 decimial places for whole numbers, so they line up when sorted?

Done.

**Pull request merged**
