### PR TITLE
Remove debug messages and change maxPolls

### PR DESCRIPTION
**Pull request by lewfish**
Some fixups for PR https://github.com/WikiWatershed/model-my-watershed/pull/517

### CODE REVIEW

**Comment by caseypt** [comment]
Cool with the fixes here, but I think that commit message style is for temporary commits that get squashed, correct @kdeloach?

**Comment by mmcfarland** [comment]
Yeah, I think that commits that are going to get merged should follow the normal conventions.

**Comment by kdeloach** [comment]
Check out the docs for [fixup commits](http://git-scm.com/docs/git-commit). They are intended to be squashed before merging.

**Comment by lewfish** [comment]
Ok, thanks for letting me know.

**Comment by rajadain** [comment]
There's still a `console.log` in line 217:

```javascript
        }).fail(function() {
            console.log('Shape endpoint failed');
            deferred.reject();
        }).always(function() {
```

**Comment by lewfish** [comment]
I wanted to keep that console message in because it shouldn't come up very often, and there's no other way to see that the error is occurring.

**Comment by rajadain** [comment]
Ah good thinking. Alright then, looks good! :+1:

**Pull request merged**
