### PR TITLE
Add save button

### PR DESCRIPTION
**Pull request by arottersman**
## Overview

- Add save button for the initial project save (displays ["Save", "Saving', "Saved"])
- Auto-save after project has been manually saved by the save button

Connects #1860 

### Demo

(This is with throttling turned on so you can see the "Saving" state)
sc2nxlhsxr

## Notes

- ~Based off of #1957, see  099d5c1 on~

## Testing Instructions

 * Pull, `./scripts/bundle.sh`
 * While not logged in
    - Draw an AoI and try to save
    - Confirm you're prompted to login/signup and after successfully doing so the project saves

* While logged in
   - Create a new project
   - Confirm changes to the scenarios and the project do not cause the project to save
   - Confirm the save button saves the projects and any created scenarios
    - All subsequent changes to the project and scenarios save automatically

### CODE REVIEW

**Comment by arottersman** [comment]
- I added 888aa20 to remove some vestigial code 
- Noticed a bug on staging while testing this. If you log in while the initial model job is still running, the job fails: `Failed to load /api/modeling/jobs/5378f08b-276f-419f-81f0-22ffd57783fb/: the server responded with a status of 404 (NOT FOUND)`. You can refresh the page to fix, but it seems like we're losing the celery job after we create the project

**Comment by rajadain** [comment]
Taking a look at this now.

**Comment by rajadain** [comment]
Having some trouble saving the projects. Demo'd to @arottersman who's looking in to it.

**Comment by arottersman** [comment]
Issue was the snippet I took out with 888aa20 ... I've corrected it, so this should be ready for another look!

**Comment by rajadain** [comment]
If a logged in user creates a new project but doesn't click "☁️ Save", but clicks "New Project", their work is lost without warning. Consider adding a confirmation modal that allows the user to recover from an accident if they mistakenly click "New Project" instead of "☁️ Save", especially likely since the buttons are right next to each other.

**Comment by rajadain** [comment]
When I start logged out, and then sign in with an existing account, the workflow works. But if I sign up with a new account, after signing up and in, the project is not saved. Furthermore, the project menu doesn't populate with anything:

image

Also, clicking "☁️ Save" doesn't do anything, and the project cannot be saved.

**Comment by arottersman** [comment]
> If a logged in user creates a new project but doesn't click "☁️ Save", but clicks "New Project", their work is lost without warning. Consider adding a confirmation modal that allows the user to recover from an accident if they mistakenly click "New Project" instead of "☁️ Save", especially likely since the buttons are right next to each other.

I think this would be better to address in #1863

**Comment by arottersman** [comment]
Applying some changes from #1970 to fix the sign up error here. Thanks for catching that!

**Comment by arottersman** [comment]
Should be fixed.

**Comment by rajadain** [comment]
Taking another look.

**Comment by rajadain** [comment]
Friendly reminder to squash before merging.

**Comment by arottersman** [comment]
Yeah, the callback passing makes me a little uncomfortable, too. It seems like the login/signup modals should be wrapped up as `Deferred` objects. 

Thanks for reviewing!

**Pull request merged**
