### PR TITLE
Limit bounding box for CUAHSI searches

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Add bounding box search constraint to CUAHSI results. We don't add this limit to other APIs because they are much faster (CINERGI), and often times don't have results if the bounding box is too narrow (CINERGI), or simply don't take a bounding box parameter (Hydroshare).

I chose a limit of 1,500 km² after some trial and error, but we can change it in the future. This should be in the HUC-10 range, when applied to AoIs. Currently we run the visible map bounds, so if you select a HUC-10 the actual bounds will be much larger.

Connects #1851 

### Notes

At first I did the server side check, but later did the client side. Not sure if we still need the server side, but since a large search can actually bring our server down we should have some sort of check there. On the other hand, this may be accounted for in #1989 

## Testing Instructions

 * Check out this branch, `bundle`
 * Go to [:8000/search?bigcz](http://localhost:8000/search?bigcz)
 * Ensure that you cannot search for WDC / CUAHSI results if the bounds of the map view exceed 1,500 km².
 * Try zooming in and out. Try switching tabs. Ensure behavior is consistent and sensible.

### CODE REVIEW

**Comment by arottersman** [comment]
Taking a look now!

**Comment by rajadain** [comment]
Regarding the irksome behavior described above, this could be addressed by not re-searching every time a tab is clicked, as requested in #1960. Having an explicit button for triggering the search would be better.

**Comment by arottersman** [comment]
I agree, not re-searching and having an explicit search button would help. I think there'd still be some cause to disable/hide the tab — after #2006 the bbox will more static in the sense that if the AoI is too big the CUASHI tab is never worth clicking.

**Comment by rajadain** [comment]
> disable/hide the tab

Ah I see what you're saying. That's great idea, will add to this.

**Comment by rajadain** [comment]
> disable/hide the tab

On second thought, that's a nicety which I think we can defer till later. Adding a "disabled" state to tabs, and a conditional tooltip that informs the user why it is disabled is non-trivial, and best done in its own pointed card.

/cc @ajrobbins

**Pull request merged**
