### PR TITLE
Add command for getting list of DRB users

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Adds a management command to get a list of all DRB users. For this, we took the [shapefile of ZIP codes from TigerLines](https://catalog.data.gov/dataset/tiger-line-shapefile-2015-2010-nation-u-s-2010-census-5-digit-zip-code-tabulation-area-zcta5-na) and intersected it with [the DRB perimeter](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/data/drb_perimeter.json) and got a [list of ZIP codes](https://github.com/WikiWatershed/model-my-watershed/files/1455542/zip2.csv.txt). See https://github.com/WikiWatershed/model-my-watershed/issues/2330#issuecomment-342974255

This list is then used to filter users that have listed such a ZIP code in their profile.

Connects #2330 

### Demo

```bash
> kj manage drbusers
+ ARGS=drbusers
+ [[ 1 -eq 1 ]]
+ [[ drbusers == runserver ]]
+ vagrant ssh app -c 'cd /opt/app && envdir /etc/mmw.d/env ./manage.py drbusers'
id,username,organization,user_type,country,postal_code
"1","test1","Azavea","University Professional or Research Staff","US","19103"
"8","test3","Azavea","Commercial/Professional","US","19103"
"12","test7","Azavea","Unspecified","US","19103"
Connection to 127.0.0.1 closed.
```

### Notes

Currently we have very little validation on user entry (for example we do not validate that ZIP codes are numeric and five digit, although I guess this to support international entry), so the data can be a little noisy.

For production, someone will have to SSH in to the App VM and then run:

```bash
envdir /etc/mmw.d/env python manage.py drbusers > drbusers.csv
```

## Testing Instructions

 * Check out this branch and run `./scripts/manage.sh drbusers`
 * Ensure all the correct users show up, and any users with missing ZIP codes or those outside the DRB are not included

### CODE REVIEW

**Comment by ajrobbins** [comment]
So the idea here then is that whenever Stroud wants the list, we would run this command and send them the output? Just trying to nail down the workflow.

**Comment by mmcfarland** [comment]
The issue specifies that this mechanism should "track" user data.  That idea isn't defined at all, but I don't think it's accommodated with this either.  Can @ajrobbins explain the goal there and how we might accommodate it?  My suggestion would be that it tie into the proposed work we describe in https://github.com/WikiWatershed/model-my-watershed/issues/2451

**Comment by ajrobbins** [comment]
Just chatted with @mmcfarland  - this card/PR should just be to pull the user data for users identified by their ZIPs to be in the DRB, so it accomplishes that goal.

**Comment by rajadain** [comment]
> whenever Stroud wants the list, we would run this command and send them the output?

Yes.

I went the manage command route because we don't have an admin reporting interface for MMW. If something like that is developed in the future a similar query can be incorporated therein. In the interim, this should suffice.

The discussion above seems to be in agreement, so I'm going to merge this in.

Thanks for reviewing!

**Pull request merged**
