### PR TITLE
Improve info message in manual entry UI

### PR DESCRIPTION
**Pull request by lewfish**
We've improved the info message in the manual entry UI. See below. To test, make sure info message makes sense for all BMPs.

screen shot 2016-05-27 at 3 10 25 pm 2

Connects #1343

### CODE REVIEW

**Comment by lewfish** [comment]
Added a commit to convert UrbLength to km

screen shot 2016-05-31 at 12 03 37 pm 2

**Comment by rajadain** [comment]
We changed the display to divide by 1000 for KM units, but wouldn't we also have to change the data output to be multiplied by 1000? Or does that always use the percentages?

**Comment by lewfish** [comment]
> We changed the display to divide by 1000 for KM units, but wouldn't we also have to change the data output to be multiplied by 1000? Or does that always use the percentages?

Looking at this again, I think we just forgot to divide UrbLength by 1000. Then we won't need to do the conversion on the frontend.

**Comment by rajadain** [comment]
UrbLength should be in meters according to the [GMS File Key Spreadsheet](https://docs.google.com/spreadsheets/d/12hsklRHwl6sNum0xPk6d5Cw6ONDA3X6BR5-Pc-NwJBc/edit#gid=0) and the [GMS documentation](https://docs.google.com/document/d/1M5GgnLGfJvv3mZUjoVFpkGZZ4dX6oqqq9n0sZgk7KDs/edit)

**Comment by lewfish** [comment]
> UrbLength should be in meters according to the GMS File Key Spreadsheet and the GMS documentation

Then things are as they should be. The output var is either in km or is a %

**Comment by rajadain** [comment]
+1 tested, makes sense!

**Pull request merged**
