### PR TITLE
Add AoI outline to mask layer.

### PR DESCRIPTION
**Pull request by caseypt**
* Add a white border to the area of interest mask layer for
aesthetic purposes.

**To test:**
- Draw or select an area of interest.

selection_048

Connects to #342

### CODE REVIEW

**Comment by mmcfarland** [comment]
Yeah, I like the look!

**Comment by rajadain** [comment]
+1 works as advertised. Tried drawing new areas and loading saved projects, got a consistent white border. It indeed does look better.

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Pull request merged**
