### PR TITLE
Import `drb_catchment_water_quality` table

### PR DESCRIPTION
**Pull request by kellyi**
This PR updates the `setupdb.sh` script to get the `drb_catchment_water_quality` table from S3. 

I imported the Shapefile mentioned in #1480, added a spatial index, `pg_dump`ed it from the instance of Postgres running on my Services VM, then uploaded it to S3. This update adds the filename to the list of files to get when using the `-q` option to get water quality data.

**Testing**
- get this branch, `vagrant up`, then `vagrant ssh app` and `cd /vagrant/scripts/aws`
- run `./setupdb.sh -q` to import the DRB catchment water quality data
- inside the services VM, run `psql -h localhost -U mmw` to login
- run `SELECT COUNT(*) FROM drb_catchment_water_quality;` and verify that you see

```sql
 count 
-------
 15004
(1 row)
```

- run `\d drb_catchment_water_quality` and verify that you see this output:

```sql
 
                                      Table "public.drb_catchment_water_quality"
   Column   |            Type             |                                 Modifiers                                 
------------+-----------------------------+---------------------------------------------------------------------------
 gid        | integer                     | not null default nextval('drb_catchment_water_quality_gid_seq'::regclass)
 nord       | numeric(10,0)               | 
 areaha     | numeric                     | 
 pop10      | numeric(10,0)               | 
 tn_tot_kgy | numeric                     | 
 tn_urban_k | numeric                     | 
 tn_riparia | numeric                     | 
 tn_ag_kgyr | numeric                     | 
 tn_natural | numeric                     | 
 tn_pt_kgyr | numeric                     | 
 tp_tot_kgy | numeric                     | 
 tp_urban_k | numeric                     | 
 tp_riparia | numeric                     | 
 tp_ag_kgyr | numeric                     | 
 tp_natural | numeric                     | 
 tp_pt_kgyr | numeric                     | 
 tss_tot_kg | numeric                     | 
 tss_urban_ | numeric                     | 
 tss_ag_kgy | numeric                     | 
 tss_natura | numeric                     | 
 tss_rip_kg | numeric                     | 
 geom       | geometry(MultiPolygon,4326) | 
Indexes:
    "drb_catchment_water_quality_pkey" PRIMARY KEY, btree (gid)
    "drb_catchment_water_quality_geom_idx" gist (geom)
```

Connects #1480

### CODE REVIEW

**Comment by kellyi** [comment]
^ Build failed due to the Postgres API client libraries issue, but the PR should work on your local if your Services VM is already set up.

**Comment by kellyi** [comment]
Thanks for taking a look! I'll wait til `release` has been merged into `develop` to rebase then merge this.

**Comment by rajadain** [comment]
Suit yourself. We know the reason for the failing check, and this wouldn't really conflict with anything on `release/1.15.0`. `develop` should be all caught up tomorrow evening, so you wouldn't be waiting very long in either case.

**Comment by kellyi** [comment]
Note: it turns out I'd originally imported the shapefile to Postgis in the wrong projection, which I discovered when setting up the tiler to display the data for #1482.

I imported it again in the proper projection, then uploaded the new `sql.gz` file to S3 under the same name. Here's what that current data looks like in QGIS, placed above the `dep_municipalities` data for reference:

screen shot 2016-10-05 at 9 01 39 am

**Comment by ajrobbins** [comment]
@kellyi did you by chance save your scripts somewhere (a la last RRP retro)?

**Comment by kellyi** [comment]
@ajrobbins The script to pull the data down's committed here. I didn't save the script to import it but it was effectively this command from the command line to import:

```
shp2pgsql -s 32618:4326 finallateralshed_92916.shp drb_catchment_water_quality | psql -h localhost -U mmw -p 5432
```

and something like this to `pg_dump` it to upload to s3:

```
pg_dump --clean --if-exists --no-owner --table=drb_catchment_water_quality --database=mmw | gzip --best > drb_catchment_water_quality.sql.gz
```

Aside from that, the only SQL here was to create the spatial index which was:

```sql
CREATE INDEX drb_catchment_water_quality_geom_idx ON drb_catchment_water_quality USING gist (geom)
```

There weren't any additional joins or anything; essentially the SQL part just set up a brand new table and added the spatial index. Happy to commit that stuff somewhere if we'd like, though!

**Comment by kellyi** [comment]
@azavea-bot rebuild

**Comment by kellyi** [comment]
Tests passed! Merging now.

**Pull request merged**
