### PR TITLE
Micro site screenshot fixes

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Fixes issues with micro site screenshots:

 * Slider remained fixed in the screenshot, instead of reflecting true value
 * Squiggly arrows would not render
 * Heading would be garbled
 * Some tiles would be cut off on the right

## Testing Instructions

Log in to [ITSI Staging](https://learn.staging.concord.org) as `tstudent2`, and select the MMW Micro 7461a830 activity. Open it and take screenshot from the button below:

image

## Demo

**Old**

image

**New**

image

Connects #954 
Connects #847 
Connects #789

### CODE REVIEW

**Comment by rajadain** [comment]
I will setup a new activity running of `ngrok` from my local tomorrow morning, and will comment here when that is available to test.

**Comment by rajadain** [comment]
Ready for testing now. Log in to ITSI as `tstudent2` and run the MMW MICRO 7916D5AD activity:

image

**Comment by caseypt** [comment]
+1. Looks good. Nice set of fixes.

screen shot 2015-10-16 at 10 31 59 am

**Comment by rajadain** [comment]
Added more context to slider value change in commit message for 5bad461

**Pull request merged**
