### PR TITLE
Add Mid-Atlantic ARA layer

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Add painted ARA layer to Coverage Tab. Exact names and descriptions subject to change. There also isn't a legend, but since there's only one value, do we need it?

Connects #2886 

## Testing Instructions

* Check out this branch
* Go to [:8000/](http://localhost:8000/) and select the "Mid-Atlantic ARA" layer in Coverage tab
* Ensure it is available, works as expected, and has an opacity slider
* Go to [:8000/?bigcz](http://localhost:8000/?bigcz) and ensure the layer is not available

### CODE REVIEW

**Comment by rajadain** [comment]
What text should we have here? /cc @ajrobbins @aufdenkampe

**Comment by aufdenkampe** [comment]
@rajadain, the ARA layer is the Active River Area (ARA) developed by The Nature Conservancy (TNC). See 
https://www.conservationgateway.org/ConservationByGeography/NorthAmerica/UnitedStates/edc/reportsdata/freshwater/floodplains/Pages/default.aspx

The layer label, should appear in the Layer selector, Coverage Grid tab, listed under "Mean Monthly Temperature" and above "PA Urbanized Areas and Municipalities". Use this label text:
- **Active River Layer - NE & Mid-Atlantic**

For the legend/tooltip, use this text:
- The Active River Area (ARA) was developed by The Nature Conservancy (TNC) to identify areas within which important physical and ecological processes of the river or stream could occur. For more information and data sources, see [WikiWatershed Technical Documentation on Coverage Grids](https://wikiwatershed.org/documentation/mmw-tech/#overlays-tab-coverage).

Ideally, we would also expose some of this information in our _Analyze "Streams" pane_, including eventually providing an Analysis of ARA area in our AoI. Given our current funding, I'm wondering if we might just add this text to the bottom of the Analyze "Streams" pane, below the "Download this data" button:

> **Other Relevant Data:**
> - Visualize the [Active River Area for the NE & Mid-Atlantic region](https://wikiwatershed.org/documentation/mmw-tech/#overlays-tab-coverage), from the map's Layer selector, under the Coverage Grid options. 

Ideally would add similar text under the _Analyze Land pane_, referencing the Future Land Use layers:
> **Other Relevant Data:**
> - Visualize the [DRB Urban Land Future Projections](https://wikiwatershed.org/documentation/mmw-tech/#overlays-tab-coverage), from the map's Layer selector, under the Coverage Grid options.

**Comment by ajrobbins** [comment]
Thanks for responding, @aufdenkampe ! Since your request regarding exposing some of this in the Analyze tab is separate from this issue's original intent, I'm spinning it out into a separate card.

**Comment by rajadain** [comment]
I've renamed and re-ordered the layers to fit the above. Tooltips for this and #2889 will be added as part of #2397.

**Comment by rajadain** [comment]
Layer order demo:

**Comment by aufdenkampe** [comment]
Looks good (although scroll was a bit too fast to really check everything).

**Comment by rajadain** [comment]
Sorry about that. Here's an artificially expanded layer picker showing all the entries:

image

**Comment by aufdenkampe** [comment]
Thanks! That actually helped me find a typo that I introduced!

This is the correct title for ARA:
- Active River Area - NE & Mid-Atlantic

I had typed "Layer" instead of "Area".

**Comment by rajadain** [comment]
Nice! Fixed in 687a8e6

**Comment by rajadain** [comment]
Thanks for reviewing! Merging now.

**Pull request merged**
