### PR TITLE
Ensure Celery tasks get routed to matching worker

### PR DESCRIPTION
**Pull request by caseycesari**
## Overview

Configure Celery to only send tasks to workers that match the specified stack color. This prevents tasks from getting assigned to an old worker in a blue/green deployment.

Configuration is largely based on http://docs.celeryproject.org/en/latest/userguide/routing.html#manual-routing and https://github.com/rduplain/celery-simple-example.

Connects to #2374

## Testing Instructions

- **Before pulling down this branch**, make sure your worker VM is up.
- Next, **still don’t pull down this branch**, but apply the attached patch to bring up another worker. [pr.patch.zip](https://github.com/WikiWatershed/model-my-watershed/files/1422474/pr.patch.zip)
- When both workers are running, in two separate terminal windows (it’s easier to see if it’s one window split into two panes), run both `./scripts/debugcelery.sh` and `./scripts/debugworkerm.sh`.
- Start the app using `./scripts/debugserver.sh`.
- Select an AoI, and switch back to the terminal. You should see tasks being routed to both workers.
- Select MapShed, and switch back to the terminal. Again, you should see output from both workers because the tasks for MapShed are being split amongst both of them.
- Now, pull down this branch. 
- Restart the debug scripts for both workers. You should note that, in the start up text, you see output like:

```
> celery           exchange=direct key=task.{Color}
````

Previously, it looked something like:

```
> celery           exchange=celery(direct) key=celery
````
- The original worker should output `key=task.Black`, and the new worker should output `key=task.Magenta`.
- Return to the app, and kick off a mashed job. Only the Magenta worker should get tasks.
- Edit [Line 73](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/base.py#L73) of the settings file and change the value to `Black`. Restart the app server.
- Kick off another modeling job. Tasks should now only be sent to the Black worker.

### CODE REVIEW

**Comment by caseycesari** [comment]
Tagging @hectcastro and @rajadain just to have a look. It's a bit of a pain to get setup for testing.

**Comment by rajadain** [comment]
@azavea-bot rebuild

**Comment by rajadain** [comment]
When we push to production, we'll have an old stack and a new stack running simultaneously. Not sure if this will prevent leaks from the old stack (even though it might in the new stack). Also not sure how to test this. Maybe with 2 `app` VMs?

**Comment by mmcfarland** [comment]
When I test this out, I'll bring up two full but separate stacks.

**Comment by hectcastro** [comment]
I can setup a test in staging that simulates what'll happen in production if the local multi-version tests aren't conclusive.

**Comment by mmcfarland** [comment]
I was able to test the following configurations by using 2 worker vms and 2 app _processes_ with different settings and colors.  The test outcome table is what I anticipated the release/prod schedule to be like:  current behavior, this release when it's mixed config, subsequent releases with both new config and then just the behavior of the production after the subsequent release.  They all behaved as expected and stuck to their own kind/color.  This makes sense because new workers are _only_ listening on an exchange that does not exist to the old workers.

_suffix `1` means `develop`, `2` means this branch_

| type | configuration | result | correct? |
| ---| ---| ---| ---|
|current |app1-black + worker1-black + worker1-magenta | distributed | :x: 
|next release|app1-black + app2-magenta + worker1-black + worker2-magenta | siloed | :white_check_mark: 
|subsequent release|app2-black + app2-magenta + worker2-black + worker2-magenta | siloed | :white_check_mark: 
|third gen|app2-black + worker2-black + worker2-magenta | siloed | :white_check_mark: 

I'm reasonably confident that this tested appropriately, but it really took some gymnastics to establish a dev environment that could represent production.  It may still be worthwhile to test this transition in staging.

**Comment by caseycesari** [comment]
@mmcfarland Thanks for the thorough review.

@hectcastro Do you want me to wait to merge this?

**Comment by hectcastro** [comment]
Will defer the decision to @tnation14 because he'll be leading the next release. If we do want to test in staging, keeping this unmerged might make it easier.

**Comment by tnation14** [comment]
I think testing this in staging would be a good idea. I can bring up a new staging stack today to see how the transition will go.

**Comment by tnation14** [comment]
Just finished testing this in staging. To test, I followed these steps:

# Phase 1 (tests the transition to using the new queue with manual routing)
- Deploy a Blue stack containing an AMI built from `cpc/fix-celery-stack-queue`. Leave current staging up as the Green stack, running code from `develop`.
    - In this phase, we have a mixed deployment; one stack is running `develop`, one stack is running `cpc/fix-celery-stack-queue`.
- On both the Green and Blue App servers, select an AoI to kick off an analysis job.
- Jobs generated on the Green App server were only handled by Green workers; Blue jobs were handled by Blue workers.

# Phase 2 (See how workers handle a changed binding key)
- Remove the Green stack running `develop`, and replace with a Green stack running a `cpc/fix-celery-stack-queue` AMI. 
    - At this point, all stacks on staging are running the code from `cpc/fix-celery-stack-queue`.
- Again, select an AoI and start an analysis job from the App server on each stack.
- Jobs were handled only by workers of the same stack color.

*Note*: It doesn't seem like this PR is what caused the issues, but `AppServer` instances were failing to start because of an incompatibility between `pandas` and `numpy`. The service failed during initialization with this error:

```python
ERROR:django.request:Internal Server Error: /health-check/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/opt/app/mmw/middleware.py", line 25, in process_request
    callback_kwargs = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/app/mmw/urls.py", line 12, in <module>
    import apps.bigcz.urls
  File "/opt/app/apps/bigcz/urls.py", line 8, in <module>
    from apps.bigcz import views
  File "/opt/app/apps/bigcz/views.py", line 15, in <module>
    from apps.bigcz.clients import CATALOGS
  File "/opt/app/apps/bigcz/clients/__init__.py", line 6, in <module>
    from apps.bigcz.clients import cinergi, hydroshare, cuahsi
  File "/opt/app/apps/bigcz/clients/cuahsi/__init__.py", line 11, in <module>
    from apps.bigcz.clients.cuahsi.details import details, values  # NOQA
  File "/opt/app/apps/bigcz/clients/cuahsi/details.py", line 10, in <module>
    from ulmo.cuahsi import wof
  File "/usr/local/lib/python2.7/dist-packages/ulmo/__init__.py", line 12, in <module>
    from . import cdec
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cdec/__init__.py", line 1, in <module>
    from . import historical
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cdec/historical/__init__.py", line 2, in <module>
    from .core import (
  File "/usr/local/lib/python2.7/dist-packages/ulmo/cdec/historical/core.py", line 57, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: iNaT not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```
I was able to workaround this by manually installing numpy 1.13 on the `AppServer`. Other than the dependency issue, It seems like this change will deploy smoothly, and tasks will get routed to the proper queues; I think that this is OK to merge.

**Comment by hectcastro** [comment]
> I was able to workaround this by manually installing numpy 1.13 on the AppServer. Other than the dependency issue, It seems like this change will deploy smoothly, and tasks will get routed to the proper queues; I think that this is OK to merge.

Please open an issue for this if you think it is something that exists on `develop`.

**Comment by tnation14** [comment]
Numpy issue fixed in #2442

**Comment by caseycesari** [comment]
Thanks for the thorough checks everyone. Going to merge.

**Pull request merged**
