### PR TITLE
Use NLCD color for popover and highlight for micro site

### PR DESCRIPTION
**Pull request by caseypt**
Use NLCD color for popover and highlight
* Set popover to use a custom template that has a dynamic
class for each land use.
* Move popover init code to app JS file.
* Add NLCD color SASS variables.

**Testing Instructions:**
- Visit the micro app.
- Verify that for each land use, the popover header and highlight color match, and that they are the correct NLCD color.
- Verify that the soil choices still use the default color.

screen shot 2015-09-28 at 11 03 59 am

I also updated the text color of the "Grassland" and "Pasture/Hay" popovers because it was hard to read with the new background colors:

screen shot 2015-09-28 at 11 08 43 am

screen shot 2015-09-28 at 11 10 31 am

Also, I created SASS variables for the NLCD colors and updated the analysis chart to use these variables. Verify that the analysis chart still uses NLCD colors:

screen shot 2015-09-28 at 11 03 34 am

Is the extra gray space between the image and the highlight a known issue? I assumed it was caused by the missing images.

screen shot 2015-09-28 at 11 04 31 am

Connects to #840

### CODE REVIEW

**Comment by rajadain** [comment]
Created #865 for the extra whitespace in thumbnails.

**Comment by rajadain** [comment]
Not sure how it looks on your screen, but I think we could use a similar dark text treatment for Wetlands:

image

**Comment by caseypt** [comment]
Re: wetlands, will do.

**Comment by caseypt** [comment]
Updated:

screen shot 2015-09-28 at 11 47 15 am

**Comment by rajadain** [comment]
+1 tested. Code look great too!

**Comment by mmcfarland** [comment]
+1

**Pull request merged**
