### PR TITLE
Remove unused scenario method getSlug

### PR DESCRIPTION
**Pull request by caseypt**
This method is no longer used.

**To test:**
- Create a new project.
- Save it.
- Visit it using the saved URL.
- Run tests

Connects to #377

### CODE REVIEW

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
+1 It would be nice to have project slugs for vanity URLs in the address bar, so maybe this code can be re-purposed.

**Comment by caseypt** [comment]
Agreed

**Pull request merged**
