### PR TITLE
MapShed Manual Entry: Design Review

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Fixes various design issues.

Connects #2976 

### Demo

Long Scenario Names:

Right-aligned Settings button, Hide Undo after click, Thousands Separator in Land Use Area:

Undo button working with dropdowns:

Also tagging @jfrankl for visual review.

## Testing Instructions

* Checkout this branch and `bundle`
* Open a MapShed project and add a scenario to it
* Go through the list of items in the original issue and ensure they have been fixed

### CODE REVIEW

**Comment by kellyi** [comment]
Can we add the thousands separator to the validation number, too?

screen shot 2018-09-24 at 11 30 24 am

**Comment by kellyi** [comment]
Not quite sure whether this is a bug but it looks like the "Conservation Practice" menu currently remains open when the land cover modal is displayed:

screen shot 2018-09-24 at 11 31 08 am

Wondering if it makes sense to have "Conservation Practice" close when the modal opens?

**Comment by kellyi** [comment]
Looks good. Everything described in the original PR comment has been remedied.

I do think we should add the thousands-separator to the validation area number as part of this PR.

For the "Conservation Practice" menu, it seems like it should close on opening another modal but that could either be part of this work or a separate issue.

**Comment by rajadain** [comment]
Added thousands separator to red diff

image.

Regarding the Conservation Tillage popup, I'm not sure if that is undesirable behavior, as a modal and a popup are different UI constructs. I'll make a separate card for that.

**Comment by jfrankl** [comment]
This looks great! Truncating long scenario names is a major enhancement.

**Comment by kellyi** [comment]
> Regarding the Conservation Tillage popup, I'm not sure if that is undesirable behavior, as a modal and a popup are different UI constructs. I'll make a separate card for that.

Sounds good.

**Comment by kellyi** [comment]
:+1:

screen shot 2018-09-26 at 10 12 18 am

**Comment by rajadain** [comment]
Made #2985 for the conservation practice popup staying open. Going to squash and merge now. Thanks for taking a look!

**Pull request merged**
