### PR TITLE
Display boundary layer search results

### PR DESCRIPTION
**Pull request by kdeloach**
## Overview

Display boundary layer search results in the geocoder autocomplete and the map.

Connects #1762

### Demo

image

## Testing Instructions

 * Configure searchable boundary layers in `layer_settings.py` depending on which boundary layers you have on your workstation
 * Run `./scripts/bundle.sh`
 * Verify that boundary layers and geocoded results show up in the autocomplete
 * Verify that picking geocoded suggestions still work
 * Verify that picking boundary layer suggestions adds the layer to the map

### CODE REVIEW

**Comment by kdeloach** [comment]
Updated the unit tests. The only remaining thing to do is to group boundary layers together in the autocomplete dropdown to match the mocked up design.

**Comment by ajrobbins** [comment]
Here is an updated wireframes of the grouped boundary layers; when there are more than 2 results in the HUC subsections, a "view more" link should appear that would expand the results to 5 total.
segmented_search_results_1
segmented_search_results_2

This can be spun off into another card, if that makes more sense to you @kdeloach .

**Comment by kdeloach** [comment]
I'll group boundary layers together but would like to do the "view more" link in a separate PR.

**Comment by kdeloach** [comment]
This is ready for review.

**Comment by arottersman** [comment]
@rajadain won't be back until Thursday :'(

**Comment by kdeloach** [comment]
Ah, thanks for the heads up. Reassigned.

**Comment by arottersman** [comment]
Overall the grouping is working, but it's disturbingly slow on my machine. It exposed some weird behavior:

qlon2dxgku

(If you watch the gif long enough you'll see results return) The incremental requests don't cancel, so despite `schuykilll` sitting in the input, you'll first see results for the letter `s`, then they'll disappear to show results for the `sch`, then again `schuykill`.

I wonder if we should:
1. Cancel requests as each new one comes in 
1. Show the results of geocoder and boundary searches independently; if geocoder results come in first, show them, and then add the boundary results to the view as soon as they've returned

**Comment by kdeloach** [comment]
I'll look into cancelling stale requests. The reason that I decided not to show results independently is because it breaks all the geocoder tests (which expect a linear sequence of actions) and I couldn't think of an elegant way to rewrite them. I'll see if there's a way I can hack it without breaking the unit tests.

**Comment by kdeloach** [comment]
I'm also going to add a minimum character limit on the boundary search endpoint since doing a full text search for a single letter is pointless.

**Comment by arottersman** [comment]
Sounds good! Should we make a separate issue for what happens once you get to draw?

**Comment by kdeloach** [comment]
Could you elaborate on that?

**Comment by kdeloach** [comment]
Unit tests are passing on Jenkins.

**Comment by arottersman** [comment]
During RRP we talked about how it's not clear what should happen after selecting a boundary result...currently it displays an AOI you can't intuitively select to take to analyze/model. 

Some possibilities I think were
- go right to analyze/model with the shape
- turn on the corresponding boundary select tool for the search-selected shape

**Comment by kdeloach** [comment]
My recollection is that we decided to keep the existing behavior to zoom to the boundary location. You can use the "Select by boundary" draw tool to analyze it if you want.

**Comment by arottersman** [comment]
My bad  — I think I selectively missed that part of the conversation

**Comment by kdeloach** [comment]
Updated with these changes:

* Cancel pending requests before making new ones
* Display geocode/boundary results independently
  * This may be hard to see since we don't clear the previous results before fetching new ones
* Better "loading" indication

**Comment by arottersman** [comment]
Cool, this is working pretty naturally now!

 One small, buggish thing is the `working` indicator (the spinner) turns off when the first results return:

(I had "dog" in the bar, and it's now working on "schuy" but you can't tell)
screen shot 2017-04-18 at 2 55 00 pm

Consider keeping the spinner until all polling completes.

**Comment by kdeloach** [comment]
Fixed a bug where the loading icon state was not always consistent, and another bug where results would not appear until both requests completed initially.

**Comment by kdeloach** [comment]
Thanks.

**Pull request merged**
