### PR TITLE
Use Leaflet.Draw fork that supports touch

### PR DESCRIPTION
**Pull request by rajadain**
## Introduction

We are switching to [Michael Guild's fork](https://github.com/michaelguild13/Leaflet.draw) of [Leaflet.Draw](https://github.com/Leaflet/Leaflet.draw/) to get support for touch screens. There are a number of considerations that must be taken into account.

### Original Issue

The original issue on Leaflet.Draw is here: https://github.com/Leaflet/Leaflet.draw/issues/2. The conversation on that thread started with a few contributors who came up with various solutions which worked in some cases and didn't in others, until Guild came along and essentially took ownership of the effort, and has been working on it on-and-off for more than a year now. As the conversation moves along, the comments get more and more supportive and appreciative, and the bugs become rarer and more edge-case-y. There is also some discussion about [Tom Blackmore's fork](https://github.com/tablackmore/Leaflet.draw/tree/touch), and [Jacob Toye](https://github.com/jacobtoye) (who seems to be a core developer of Leaflet.Draw) initially seemed to favor his approach. However, Guild's fork has been more active, has been used and tested by more people, and is up to date with the current Leaflet.Draw codebase.

### Pull Request

Guild has an open pull request to the main repo here: https://github.com/Leaflet/Leaflet.draw/pull/285. Initial conversation is about syntax, but eventually people start testing it and liking it, and Toye chimes in with his approval and a promise to carve out time for Leaflet.Draw in the future. The main issues people have with the PR are:

 * It has too many commits, should be squashed to make more readable
 * It has other experiments, particularly related to styling, that are unrelated to the core touch functionality, that people want to be separated out
 * There is some discussion of errors in Internet Explorer, not sure if they relate to click or touch functionality
 * He seems to have done more work in private somewhere, which hasn't been added to his GitHub yet

But overall consensus is positive, with the hopes that his work will be merged into the main Leaflet.Draw repo at some point in the near future. The main blocker for that effort is simply time on the part of both Guild and Toye, who had not been able to pay much attention to this, until recently when activity has started again.

## Concerns

 1. So far we have been using Leaflet.Draw 0.2.3, but all of Guild's work is up-to-date with `master`, thus we are not just getting the touch support, but all sorts of changes to Leaflet.Draw.
 2. Guild's repo is very much a development repo, not a release one. There aren't any tests, or tags, or releases. The [current head](https://github.com/michaelguild13/Leaflet.draw/tree/e2fe3a4c176979235845e8fbb1c5017414035765) seems to work well enough, and that's what I've pinned in `package.json`. All our existing tests are passing, and prelimnary testing in Chrome and Mobile Safari on iOS has been flawless. But we need to test more.

## Testing

To test this, check out the PR branch and run 

```bash
$ ./scripts/npm.sh install
$ ./scripts/bundle.sh --vendor
```

Then check with various browsers and devices that the map is usable:

 * Test drawing a polygon Area of Interest
 * Test delineating a watershed
 * Test zooming and panning with the polygon drawn
 * Test drawing modifications

Tested on:

 * [x] Chrome 43.0.2357.130 (64-bit) on Mac OS X 10.10
 * [x] Mobile Safari on iPad Mini 2 running iOS 8.3 — Modifications needed to be tapped twice, the first time simulated a hover and the second a click.
 * [x] :warning: Mobile Safari on iPad 2 running iOS 8.1 — Had some odd behavior when entering `/analyze` view. Modifications needed to be tapped twice, the first time simulated a hover and the second a click.
 * [x] Mobile Safari on iPhone 6 running iOS 8.3
 * [x] Chrome 43.0.2357.61 on iPhone 6 running iOS 8.3
 * [x] Firefox 38.0.5 on Mac OS X 10.10
 * [x] :warning: Safari 8.0.6 on Mac OS X 10.10 — Had some odd behavior when entering `/analyze` view.
 * [x] Chrome 43.0.2357.93 on Moto E running Android 5.1 Lollipop
 * [x] Firefox on Nexus 5 on Android 4.4 KitKat
 * [x] Chrome on Nexus 7 running Android 5.0 Lollipop
 * [x] Chrome on Linux
 * [x] Firefox on Linux
 * [x] Chrome 43.0.2357.130 m on Windows 7 Enterprise SP1
 * [x] Firefox 38.0.5 on Windows 7 Enterprise SP1
 * [x] :warning: Internet Explorer 11.0.9600.17843 on Windows 7 Enterprise SP1 — Precipitation Slider does not show up. SVG patterns do not show up. See #504 
 * [x] :x: Internet Explorer 11.0.9600 on Surface Pro 3 running Windows 8.1 Pro — The site **does not render at all** because IE on Surface does not support the touch events in Guild's repo and throws an error.
 * [x] :x: Chrome 43 on Surface Pro 3 running Windows 8.1 Pro — Touch interaction works (when you touch the screen with a finger), but **click interaction (with trackpad and stylus) fails to close the polygon, instead keeps adding new overlapping points.**
 * [x] :x: Firefox 38 on Surface Pro 3 running Windows 8.1 Pro — Click interaction works (when you use trackpad or stylus), but touch interaction fails to register a `mouseclick` event. **Each touch acts as a hover / `mousemove` event instead of a click.**
 * [ ] IE Mobile on Windows Phone

:warning: = Minor problems, possibly unrelated to touch functionality
:x: = Major problems related to touch functionality

I will leave this PR open until I've tested at least on the above platforms.

Connects #476

### CODE REVIEW

**Comment by hectcastro** [comment]
@azavea-bot rebuild

**Comment by mmcfarland** [comment]
Thanks for listing out the relevant considerations to evaluate.  As we discussed offline, though this should make us a little nervous, the touch support is something of must-have for the client, so this is a necessary risk.  I think we just need to remain active on the issue/PR, encourage its getting merged and leave an outstanding issue in our repo to follow up when it is.  If instability or other problems occur, we'll have to re-evaluate then, but I'm at least buoyed by the community response to this fork.

**Comment by kdeloach** [comment]
Nice write up.

**Comment by rajadain** [comment]
I've just updated the main comment with more testing information. The general feel is:

 * New Leaflet.Draw code seems to work in all existing environments, so it seems like we are unscathed by those updates
 * The touch functionality works great in both laptops and phones / tablets, but fails completely on dual-mode devices like the Surface Pro 3. With the old plugin (Leaflet.Draw 0.2.3 on `develop` and `master`), click functionality (but not touch) works in Firefox and Chrome. On Internet Explorer, even click doesn't work, but the page renders.
 * There are other issues, unrelated to this change, present in Safari and Internet Explorer

I will test further today.

**Comment by rajadain** [comment]
Created #504 for Internet Explorer issues.

**Comment by rajadain** [comment]
A potential large deal breaker is that click functionality is impeded in Chrome on Windows when running on a touchscreen: The polygon refuses to close, and clicking on the starting point simply adds more overlapping points instead of closing the polygon.

Internet Explorer won't even render the page.

This can be alleviated by adding a button, only visible during drawing, that allows one to close the polygon.

**Comment by mmcfarland** [comment]
I got confirmation from Stroud today that they are comfortable supporting iPad and desktop browsers specifically, even knowing the current limitations with the dual-input devices like the Surface.  We should track the life of this fork so we can revert to the origin, but let's deal with "minor" devices and their problems as their reported.

**Comment by rajadain** [comment]
I'm subscribed to the [original issue](https://github.com/Leaflet/Leaflet.draw/issues/2) and the [pull request](https://github.com/Leaflet/Leaflet.draw/pull/285), as well as [the fork](https://github.com/michaelguild13/Leaflet.draw), so should be notified of any activity there. I'm going to rebase this on top of `develop` and run a final test to ensure it still works, and will then merge.

**Comment by rajadain** [comment]
Created #526 and #527 for Android and iPad issues respectively. While this PR adds touch support, we need some more work to polish the UX in touch devices. Those issues are there to track whatever issues we discover as we test.

Rebasing on `develop` was straightforward. Tested on iPad and Android, as well as traditional non-touch "desktop" browsers to ensure that things still work.

**Comment by ddproxy** [comment]
Hey guys, I'm working on a leaflet.draw fork that will be needing IE support for drawing polygons etc.
https://github.com/ddproxy/Leaflet.draw

Just wanted to inject myself into this conversation going forward. Cool work with watershed by the way!

**Comment by SRGDamia1** [comment]
I just got a report that this problem is also coming up in touchscreen Chromebooks.

**Comment by rajadain** [comment]
I just put up #1421 to upgrade Leaflet.Draw to 0.3.0, but that doesn't fix the issues in Chrome and Firefox unfortunately. IE and Edge now work correctly though, which may hold our Windows users over for a bit. See https://github.com/WikiWatershed/model-my-watershed/issues/649#issuecomment-239912341 for details.

**Pull request merged**
