### PR TITLE
Fix geocoding

### PR DESCRIPTION
**Pull request by caseypt**
Allow cross-domain AJAX. Only use CSFR internally.
* Remove option to deny cross domain AJAX requests.
* Check if requested URL is external before attaching
CSRF header.
* Add tests for CSRF module.

**To test**:
- Navigate to the home page.
- Try using the address search input.
- Try loading and saving a project.
- Run the tests.

Connects to #336

### CODE REVIEW

**Comment by rajadain** [comment]
Marvelous work on the tests! They all pass and exercise all cases.

Tested the UI and found it to be working satisfactorily as well. CSRF Safe and External Domain requests never have an `X-CSRFToken` header, and all other requests always do:

image

All requests succeed.

+1

**Comment by caseypt** [comment]
@azaveaci rebuild

**Comment by caseypt** [comment]
@azaveaci rebuild

**Comment by caseypt** [comment]
@azaveaci rebuild

**Pull request merged**
