### PR TITLE
Rename options under "Draw Area" dropdown

### PR DESCRIPTION
**Pull request by kdeloach**
Having a "Draw Area" option in the "Draw Area" dropdown looked funny.

image

### CODE REVIEW

**Comment by jamesmcclain** [comment]
Tested, +1

**Comment by jamesmcclain** [comment]
Arguably, the label "draw area" is kind of strange as well, given that you do not always draw.  This is an improvement, though.

**Comment by kdeloach** [comment]
Yeah, I was thinking about changing that to "Select Area" but didn't want to change too much.

**Comment by jamesmcclain** [comment]
That makes sense.

**Comment by caseypt** [comment]
+1.

**Pull request merged**
