### PR TITLE
Faster bundle

### PR DESCRIPTION
**Pull request by kdeloach**
I've added a few flags to the bundle script which should make rebuilding a lot faster.

1. The vendor bundle rarely changes so it is no longer generated by default. Use the `--vendor` flag instead.
2. Test bundles are no longer generated by default. Use the `--tests` flag instead.
3. Created a vendor bundle for tests.
4. Moved d3 to the vendor bundle.

**Note:** You'll need to reprovision the app VM to use testem since a vendor bundle has been added to the test harness.

### CODE REVIEW

**Comment by jamesmcclain** [comment]
Perhaps this should include an update to the README file, as well.

**Comment by kdeloach** [comment]
Good idea, will update the README.

**Comment by mmcfarland** [comment]
Not sure if it would push us over the reasonable number of flags for this script, but the water_balance JS will probably, for the rest of the project, only need to be rebundled very occasionally as well.

**Comment by kdeloach** [comment]
Updated the README.

Since the water balance app is so small (only 2 files) I'd like to hold off on adding a flag just for that.

**Comment by mmcfarland** [comment]
Testing now

**Comment by lewfish** [comment]
Sorry, I didn't realize I was assigned to this until now.

**Comment by mmcfarland** [comment]
+1 Much faster for regular workflow, tests still run and app functions normally.

**Pull request merged**
