### PR TITLE
Style Opacity Slider

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

The new styling matches other leaflet plugins, works across browsers.

## Demo

image

In Chrome only, when the slider is in an active state, the thumb becomes all black:

image

## Testing Instructions

Test in various browsers.

Connects #1094

### CODE REVIEW

**Comment by rajadain** [comment]
@ajrobbins: I'd also appreciate your feedback on this.

**Comment by ajrobbins** [comment]
Found some odd behavior when testing off @rajadain's machine in Safari and Chrome - The Basemap tab is not entirely clickable, and when the bottom of that tab (outside the text) is clicked with an overlay and boundary on, the overlay disappears. The Observations and Overlays tabs behave normally. The overlay comes back when the opacity slider is moved, but disappears if the bottom of the Basemap tab is clicked again.
screen shot 2016-02-15 at 11 13 02 am

**Comment by rajadain** [comment]
Great catch! I'd rotated the slider but not the containing divs, which extended horizontally and continued to catch clicks. This has now been fixed.

**Comment by rajadain** [comment]
This PR targets a release which has since been merged onto `develop`. Opening a new one that targets `develop`.

**Comment by mmcfarland** [comment]
On my version of Chromium (`Version 48.0.2564.82 Ubuntu`), the scrollbar is horizontal.

screenshot from 2016-02-17 11 03 16

**Pull request closed without merging**
