### PR TITLE
Add statsd metrics to geoprocessing jobs

### PR DESCRIPTION
**Pull request by kdeloach**
Add timing metrics around geoprocessing jobs and SJS requests.

Connects #871

Test by verifying that statsd metrics appear for geoprocessing tasks in the graphite dashboard:

image

### CODE REVIEW

**Comment by jamesmcclain** [comment]
It looks good to me, but it might be worth checking to see if everyone's needs have been met.

For example: someone had expressed interest in knowing how much time was being spent (on average) in the Geotrellis code.  I think that this can be computed by dividing one less than the count of `histogram_finish.sjs_get` (the number of times SJS was polled) by `histogram_start.sjs_post` and multiplying by the polling interval.  If people are happy with indirect numbers like that, then everything should be good (I don't know if it is possible to get more direct numbers).

+1

**Comment by jamesmcclain** [comment]
Based on what I know of this package (which is limited), the fact that the communication with the backend code is split into two pieces would make it difficult to get the number directly.

**Comment by kdeloach** [comment]
The `sum` field for this metric captures duration so we should be able to derive average duration spent on geoprocessing jobs (and how much time we spent waiting for SJS). On the other hand, this doesn't do a good job at measuring network latency because I have not added any additional metrics inside the actual geotrellis code.

**Comment by jamesmcclain** [comment]
This is truth.

**Comment by jamesmcclain** [comment]
I should point out that virtually 100% of the time spent in Geotrellis code is network latency.

**Comment by kdeloach** [comment]
:open_mouth:

**Comment by mmcfarland** [comment]
Is `histogram_finish.sum` the cumulative time for a job to complete?  It'll be a good metric to establish the length of time for a few known boundaries, and then try those same boundaries under different proposed worker scenarios.

**Comment by jamesmcclain** [comment]
If that quantity is a time, I am not sure whether it includes the polling interval or not.

**Comment by kdeloach** [comment]
This should measure the duration of individual tasks, not the entire celery chain. Polling is not included.

**Comment by mmcfarland** [comment]
+1

**Comment by hectcastro** [comment]
Not sure that instrumenting the `mmw-geoprocessing` project would help much with tracking S3 latency either (because that happens inside of GeoTrellis Spark). I think the most effective approach would be to instrument GT with some StatsD client, and then have it expose configuration so that we can tell it where to spit metrics.

**Comment by mmcfarland** [comment]
Yeah, I think this just gets us overall timings to provide a baseline to see if any of the different approaches make an overall improvement to any of the jobs.  Unless we get something inside of the GT code, I don't know if we can a finer resolution than that.

**Pull request merged**
