### PR TITLE
HydroShare Export: Include Model Result Tables as CSV

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Exports model results for MapShed and TR-55 projects as CSVs identical to their tables to HydroShare. This is done by cycling through all scenarios in the UI, rendering the tables, exporting them, and collecting the results. The scenario switching is done in the background, and the previously user-selected scenario is reselected in the end.

The additional data gathering step, and the additional files being exported to HydroShare, delay the export process. I can see it becoming quite time taking with a handful of active scenarios. Optimizing this process is something we can look in to later as an enhancement (see #2592).

Switching through all the scenarios can potentially affect the scroll state of the sidebar.

Connects #2666 
Connects #2667 

### Notes

One of the interim commits 1272ac8 exports models as JSON, directly in the format returned from the API. Instead of omitting this work, I decided to leave it in for history.

I also had to upgrade the [`tableExport`](https://github.com/hhurz/tableExport.jquery.plugin) to the latest `1.9.9` to be able to export hidden tables. Existing functionality for downloads seems to be unaffected.

## Testing Instructions

* Check out this branch and `bundle --debug --vendor`
* Go to [:8000/](http://localhost:8000/) create a TR-55 project.
* Add a scenario. Make some modifications.
* Export the project to HydroShare. Inspect the export to ensure that all the model results are identical to the tables, and to the exports generated from the UI.
* Do the same for a MapShed project. Ensure that its values correspond as well.
* Ensure the export names match up with the specifications in the original issues.
* Ensure CSV export still functions as before.

This is a potentially complex code review. I will be available to pair on this if necessary.

### CODE REVIEW

**Comment by arottersman** [comment]
Code is looking good! Taking this for a spin now

**Comment by arottersman** [comment]
For TR-55 and Mapshed the secondary tabs (Water Quality) don't render their CSVs for hydroshare (the files are blank). I can also see the model tab getting changed to the whatever the hydroshare export is working on which is a bit undesirable. Might be easiest to set up some time tomorrow to show.

**Comment by rajadain** [comment]
> For TR-55 and Mapshed the secondary tabs (Water Quality) don't render their CSVs for hydroshare (the files are blank).

Ah sorry, this is fixed by the `tableExport` update. You'll need to `bundle --debug --vendor` to reload that dependency, and then it should be fixed.

> I can also see the model tab getting changed to the whatever the hydroshare export is working on which is a bit undesirable.

Yes this is less than ideal. However, since we're using `tableExport` which exports a rendered table, we need to render the table for each scenario before exporting it. Transforming the data model into this format would require more refactoring or duplication of logic currently used in rendering the tables, both of which sound worse than this current implementation. Hopefully these issues can be addressed in #2673, if we ever get around to it.

**Comment by arottersman** [comment]
Oh, my bad. I'll test this out with the updated `tableExport`! Everything else was working, so I bet we're good.

**Comment by rajadain** [comment]
> Oh, my bad.

No, I hadn't included in the test instructions. Just updated them now.

**Comment by arottersman** [comment]
* If you're on the analyze tab while the share export is happening, the AOI header will disappear when the export releases the tables
screen shot 2018-03-01 at 11 30 30 am
_poof!_
screen shot 2018-03-01 at 11 30 17 am

* Saw this a few times — still working on concrete steps to reproduce
```
HydroShareHTTPException at /export/hydroshare
Received status 500 Internal Server Error when accessing https://beta.hydroshare.org/hsapi/resource/d0abe6b8fd104b5d871be6cfb6b1bb9a/files/ with method GET and params None.
```

* Now that the export takes a while, we might want to have some sort of loading indicator on the share button — sometimes I'll click "New Project" or navigate away from the page, and the project won't have finished its export

Moving to other browsers now

**Comment by rajadain** [comment]
> * Now that the export takes a while, we might want to have some sort of loading indicator on the share button — sometimes I'll click "New Project" or navigate away from the page, and the project won't have finished its export

Hmm. We are adding a special class to the "Share" button when an export is active, but never got around to styling it. I'll just change the text to "Exporting ..." while sharing for now, so there's some visual feedback.

---

It occurs to me that cycling through scenarios can be really disruptive for when the export is triggered automatically. Changing the UI for a background process seems like a very fragile and error-prone idea. Ideally we would be using the model itself and nothing else. Let me see if I can think of a decent alternative.

**Comment by rajadain** [comment]
Thank you for the detailed review. After much thought I decided that doing this via the UI was just not sustainable, and we have to use the model. We probably should have been doing that all along. Anyway, I finally put up a PR #2700, which does exactly that, and am closing this in its favor.

**Pull request closed without merging**
