### PR TITLE
Celerify HydroShare Export

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Since exporting multiple files to HydroShare can take a long time, and projects with multiple scenarios can balloon the number of files really quickly, the exports would time out in some cases.

To mitigate that, we wrap the creation and updating methods for HydroShare resources in Celery Tasks, and return a Job ID instead. This frees the export from the constrains of a request-response cycle, while also not tying up a `gunicorn` worker process.

Celery Tasks have their own timeouts however, and these are set to timeout after 5 minutes. The front-end which polls for these results has the same timeout.

Since these exports take so long, as users add changes in the front-end that can keep being queued for export. But if each export takes ~4 minutes, and each single change triggers an export, we're looking at potentially hours of exports queued up. If the browser is closed, or the user navigates away during this time, the queued exports would be dropped silently. Furthermore, there is no visibility of this queue, or any sort of progress of the exports. Thus, the autosync behavior is too obfuscated with potential data loss for users, which is why the final commit disables it. The autosync options are removed from the UI, all new projects default to it disabled, and a migration turns it off for all currently-syncing HydroShare resources.

~To assist or prompt users to export to HydroShare, we can think about adding a "dirty" or "stale" flag to a HydroShare resource, that can be set when any change to a project is made, and unset when a HydroShare export finishes. This is left to a future task.~

The above has been incorporated here by comparing the last HydroShare export date with the last scenario modification date. If a scenario has been modified more recently than the last export, we add a message to the HydroShare Export modal saying so.

Connects #2885 

### Demo

image

https://beta.hydroshare.org/resource/d1f4f20cd6344b7a809552164cc512a6

image

### Notes

I also tried cutting every piece of the export into a Celery Task. That work is vieweable in this diff [hydroshare-celerification-2.patch](https://github.com/WikiWatershed/model-my-watershed/files/2250696/hydroshare-celerification-2.patch.txt). This was suboptimal because since Celery doesn't allow sharing complex objects between tasks, the HydroShare Rest Client could not be shared, and each task would have to create its own which involved making OAuth requests to HydroShare, further slowing down the process. And while splitting up into smaller tasks allowed us to have an unspecified timeout at the Celery level (since each individual task could finish under the default 90s timeout), we would still have a timeout in the front-end, so there is no getting rid of timeouts completely.

### HydroShare Recommendations

There are potential improvements that can be made to the HydroShare API which would help us significantly:

 1. **Support Bulk File Uploads**. Since the most time is spent uploading a file at a time, even though all the files are ready at once, the ability to support bulk file uploads would speed up the process significantly. Probably by an order of magnitude or more. https://github.com/hydroshare/hydroshare/issues/2859 https://github.com/hydroshare/hs_restclient/issues/86

 2. **Allow Overwriting Files**. Currently, if a file already exists in HydroShare, you cannot add it again. We have to first delete that file, then add it. This leads to updates taking twice as long as creation, because for each file we must first delete it then add it. If adding files supported overwriting, this could be done in half the time. https://github.com/hydroshare/hydroshare/issues/2860 https://github.com/hydroshare/hs_restclient/issues/87
 
 3. **Speed Up API Responses**. Currently each API request takes ~1s to turn around. If this was faster the export would be too.

## Testing Instructions

* Populate the `MMW_HYDROSHARE_SECRET_KEY` in the `app` and `worker` VMs using the "HydroShare Beta" item in LastPass
* Go to https://beta.hydroshare.org/ and setup an account if you don't already have one
* Check out this branch, `bundle`, `vagrant ssh app -c 'sudo restart mmw-app'` and `vagrant ssh worker -c 'sudo service celeryd restart'`
* Go to [:8000/](http://localhost:8000/) and log in to an account
* Go to "My Account" → "Linked Accounts" and link to HydroShare (it should automatically connect to the beta site)
* Make a new project. Add a bunch of scenarios to it (I did 11).
* Export to HydroShare. Ensure the export completes successfully.
* Once exported, re-export to HydroShare. Ensure the export completes successfully.
* Make a change to any scenario. Open the HydroShare export dialog. Ensure it has text indicating that there are new changes.
* Test both TR-55 and MapShed projects.

### CODE REVIEW

**Comment by rajadain** [comment]
Hmm, just noticed that the above demo project doesn't have GMS files. Will look into that.

**Comment by rajadain** [comment]
One strategy that could work for notifying users that they should re-export to HydroShare is to compare the last HydroShare export date with the most recent scenario update date. If a scenario was updated after the export date, then we know there are new changes. Might need to confirm that the scenario update date is available on the front end.

**Comment by rajadain** [comment]
Added a commit that indicates if a project has changed since the last export.

**Comment by caseycesari** [comment]
Taking a look.

**Comment by rajadain** [comment]
Think you may have found a genuine bug. Looking into it now.

**Comment by rajadain** [comment]
That was a great catch. I had only been testing with projects that had previously been exported to HydroShare. Doing so with a new project tripped on not having `hydroshare` defined on the project model the first time. Now we test for that before proceeding. Also renamed some variables to read better.

Ready for another look.

**Comment by rajadain** [comment]
Added a final commit that only re-exports scenarios that have changed, or have not been exported before. If you could test this one last thing, I think we'll be good to go for the near future.

Recommended tests:

* Update branch. `bundle`
* Open existing project that has been exported already. Open the dev tools and network tab.
* Re-export the project. Inspect the request. Ensure it only has Analyze files (which will be skipped on the server side), and no scenario files.
* Add a new scenario. Re-export the project. Inspect the request. Ensure it has the new scenario files.
* Edit an existing scenario (by adding a modification or something). Re-export the project. Inspect the request. Ensure it has the modified scenario files.
* Make a new project and export to HydroShare. Inspect the request. Ensure it has all scenario files.

**Comment by rajadain** [comment]
Since re-exporting existing projects takes longer than exporting them the first time (because all files have to be checked if they exist in HydroShare, and if so, deleted, then re-exported), limiting the number of files we send on the re-export significantly speeds up the process.

**Comment by rajadain** [comment]
Thanks for the multiple thorough reviews! Going to merge this now.

**Comment by rajadain** [comment]
Will squash fixups before merging.

**Pull request merged**
