### PR TITLE
Monitor: Remove Search Data Button in BiG-CZ

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Removes "Search Data" nav button in BiG-CZ which led to a now-broken state. Since all the search functionality has been subsumed in the Monitor tab beside Analyze, we no longer need the extra stage.

Also removes unused controllers, views, and templates.

Connects #2639 

### Demo

Tagging @jfrankl and @ajrobbins for visual review.

### Notes

Should the "Monitor" tab be "Search" or "Data" or something in BiG-CZ? It was previously called "Data" in this UI:

image

## Testing Instructions

* Checkout this branch and `bundle`
* Go to [:8000/bigcz](http://localhost:8000/?bigcz) and proceed to Analyze
* Ensure you don't see a "Search Data" button in the sidebar footer, and the "Change Area" button is now full width
* Ensure you can search data from the Monitor tab
* Ensure you can Change Area, select a different shape, and start a new search in the Monitor tab
* Go to [:8000/](http://localhost:8000/) and ensure Analyze and Monitor look and work as expected

### CODE REVIEW

**Comment by kellyi** [comment]
Don't see the Search Data button here:

screen shot 2018-03-05 at 3 57 07 pm

**Comment by rajadain** [comment]
Thanks for reviewing! Will wait for feedback from @ajrobbins before merging.

**Comment by rajadain** [comment]
Spoke with @ajrobbins, we decided to make the tab header "Data" for BiG-CZ to match the previous implementation. Final commit incoming.

**Comment by rajadain** [comment]
Added a commit that makes it "Data" for BiG-CZ:

image

It remains "Monitor" for MMW:

image

Will merge once green. Thanks for taking a look!

**Pull request merged**
