### PR TITLE
Add nunjucks

### PR DESCRIPTION
**Pull request by kdeloach**
Connects #79

### CODE REVIEW

**Comment by rajadain** [comment]
+1 I like that the syntax is now basically identical to the Django template syntax, making context switching much easier. From what I can read, it seems like the performance impact is minimal and it supports async function calls which is great going forward.

**Comment by mmcfarland** [comment]
+1 Templates all appear to be working.  Strange to see pythonesque code in the frontend templates, but only because I've somehow convinced myself that it's not strange to have javascriptesque code otherwise.  Luckily looks like a pretty small change overall.

**Comment by kdeloach** [comment]
I also verified that filters, blocks, and including other templates works.

**Comment by caseypt** [comment]
I can still take a look at this if need be after it's rebased.

**Comment by kdeloach** [comment]
Rebased.

**Comment by caseypt** [comment]
+1. Tested.

**Pull request merged**
