### PR TITLE
Calculate area of Area of Interest.

### PR DESCRIPTION
**Pull request by caseypt**
* Display the area of the Area of Interest in
the Analyze View header.
* Replace the default value of the analyze place
attribute with "Selected Area"
* Move area conversion method from
Modeling.ModificationModel to Core.GeoModel, and
subclass Modeling.ModificationModel and
Analyze.AnalyzeModel from Core.GeoModel.
* Switch to use metric system instead of English
system in area calculation and display per @chitchens.
* Move ModificationModel tests from Modeling
tests to Core tests.
* Add test to Modeling tests to ensure
Modeling.ModificationModel is inheriting
properly from Core.GeoModel.

**To test**:

- Draw an area to analyze.
- Note that, in the analyze window header, the area is now in sq m or sq km and that the name is "Selected Area" and not Philadelphia.
- Try the other AoI methods and verify that the analyze header changes when a new area is selected.
- Run the tests.

Connects to #264

### CODE REVIEW

**Comment by rajadain** [comment]
Consider using standard SI symbols **m&sup2;** and **km&sup2;** instead of **sq. m.** and **sq. km.** [Wikipedia](http://en.wikipedia.org/wiki/Square_kilometre) [NIST](http://physics.nist.gov/cuu/Units/units.html)

While I would favor using the HTML escape code `&sup2;`, Wikipedia and other sites use the more explicit `<sup>2</sup>` since some older default fonts might not have the [Superscript Two](http://graphemica.com/%C2%B2) character.

**Comment by rajadain** [comment]
After I draw an area, the draw tools don't go away:

image

And if I draw a new area using these tools, the calculated area is not updated.

**Comment by rajadain** [comment]
Is the terminology we're using under the hood, **Area of Interest**, a common GIS term? If so, we should consider using that instead of **Selected Area**. /cc @mmcfarland

**Comment by mmcfarland** [comment]
"Area of Interest" was just an expedient term we came up with discussing design elements initially, not sure if it is casual enough to use here, I like the generic-ness of "Selected Area" until we can figure out a good way to compute a place name (though I suspect we may never).

**Comment by caseypt** [comment]
@rajadain I'm not seeing this behavior (stale area and keeping the tools on). I'll have to check it out on your computer when I get in.

**Comment by caseypt** [comment]
@rajadain Good call on the symbols. Rebased and updated to use them.

**Comment by caseypt** [comment]
Fixing the tests.

**Comment by caseypt** [comment]
@azaveaci rebuild

**Comment by rajadain** [comment]
+1 Works perfectly now. Did the following testing:

 * Tested range of values, from very small 43 m&sup2; to very large 596,615,995 km&sup2; and it calculates correctly
 * The behavior of draw controls being visible in analyze view now no longer happens. It may have been an artifact of faulty testing on my part, either faulty bundling or accidental caching of scripts. It is not there anymore.
 * Going back from analyze to draw view and then drawing a new area calculates area correctly
 * Going forward from analyze to model view and then going back shows the calculated area correctly
 * Units are now shown in more standard form
 * Tested using manually drawn area and congressional districts
 * Tested on Chrome and Firefox

**Comment by rajadain** [comment]
I was actually able to reproduce the accidentally visible draw tools on both your branch and on `develop`, so it is not an artifact of the work done here. Created #314 for it.

**Comment by mmcfarland** [comment]
+1 Tested and looks good.

**Pull request merged**
