### PR TITLE
Load vizer layers asyncronously

### PR DESCRIPTION
**Pull request by mmcfarland**
Vizer Observation layers were requested async, but the layer control was
not rendered until their successful return.  This caused the control to
disappear when the Vizer API was down.  This commit updates the layer
control with vizer layers as they are returned, without waiting on them
to render.  If there are failures in loading the UI will report a
message on the observation tab.

Connects #1108 

To test:
* First make sure that the observation overlays are showing and loading to the map (if the API is up, it is at the time of this writing)
* Alter the `$.getJSON(vizerUrls.layers)` line in VizerLayers.js to cause an error (appending a random string to the request will work: `$.getJSON(vizerUrls.layers + 'foo')`.  
* Rebundle and reload the page.  The layer control should exist and there should be a basic error message in the observation panel.

### CODE REVIEW

**Comment by mmcfarland** [comment]
@azavea-bot rebuild

**Comment by caseypt** [comment]
+1. Tested. Code looks good. 

screen shot 2016-01-28 at 1 27 12 pm

**Comment by lewfish** [comment]
+1, tested

**Comment by mmcfarland** [comment]
These tests pass locally.  @azavea-bot rebuild

**Pull request merged**
