### PR TITLE
Style Opacity Slider

### PR DESCRIPTION
**Pull request by rajadain**
#1152 against `develop`.

Connects #1094

### CODE REVIEW

**Comment by mmcfarland** [comment]
On my version of Chromium (`Version 48.0.2564.82 Ubuntu`), the scrollbar is horizontal.

screenshot from 2016-02-17 11 03 16

**Comment by mmcfarland** [comment]
Firefox, too.  Does this seem like a bundling problem?  The styles don't look like yours in the screenshots and they _do_ look like the old sliders from Christopher's mockups.

screenshot from 2016-02-17 11 18 23

**Comment by mmcfarland** [comment]
Sliders are building correctly and look good, but it's a little hard to recognize them as a slider for opacity.

* Is there a way to keep a little track line down the center that makes it look more traditionally like a slider?
* Can we add a tool tip or something to the handle to read "Overlay Opacity" or something?

**Comment by rajadain** [comment]
Added tooltip and a visual track, although it renders differently in different browsers:

Chrome on Mac:
image

Safari on Mac:
image

Firefox on Mac:
image

IE 11 on Windows 7:
image

Firefox on Windows 7:
image

Chrome on Windows 7:
image

Perhaps unsurprisingly, IE is the biggest disappointment, because it renders borders _over_ the slider thumb, rather than _under_ it like everybody else. Still, I don't think it is unusable, and probably an improvement. The tooltip does help as well.

image

**Comment by rajadain** [comment]
Just pushed a fix for Firefox:

image

**Comment by mmcfarland** [comment]
Great improvement, +1

screenshot from 2016-02-17 15 26 27

**Pull request merged**
