### PR TITLE
Show data catalog results on map

### PR DESCRIPTION
**Pull request by kdeloach**
## Overview

Displays all search results on the map. Hover over a search result
to highlight the geom. This also improves the API by returning
GeoJSON for each result instead of a bounding box, to support
points, polygons, and multipolygons.

Connects #1940

#### CINERGI

image

image

#### CUAHSI

image

image

### Notes

Spatial fields are not available for HydroShare so there's nothing to draw.

## Testing Instructions

* Run `./bundle.sh`
* Go to [http://localhost:8000/search](http://localhost:8000/search)
* Try different CINERGI and CUAHSI searches
* Verify that shapes appear on the map
* Verify that hovering over results highlights the corresponding shape

### CODE REVIEW

**Comment by rajadain** [comment]
One interesting behavior, which I don't if it can be fixed or should be at this stage, is that the geometries disappear when dragged off the map, and don't appear until dragging stops when brought back into view:



But it's not a deal breaker, so we probably shouldn't spend too much time thinking about it.

**Comment by kdeloach** [comment]
Interesting. I don't we're doing anything special that would cause this behavior. I'll see if I can reproduce this issue.

**Comment by mmcfarland** [comment]
> disappear when dragged off the map, and don't appear until dragging stops

This is actually the normal Leaflet behavior, I imagine it removes svg elements off screen to save memory.  You can sketch a shape on http://geojson.io and observe the same effect.

**Comment by kdeloach** [comment]
Oh, I didn't realize you were holding the mouse pressed down for so long. Why would you do that? :stuck_out_tongue:

**Pull request merged**
