### PR TITLE
Upgrade Geoprocessing to 0.3.2

### PR DESCRIPTION
**Pull request by rajadain**
Includes https://github.com/WikiWatershed/mmw-geoprocessing/pull/18

Connects https://github.com/WikiWatershed/model-my-watershed/issues/1015

### CODE REVIEW

**Comment by jamesmcclain** [comment]
Have the features that this PR introduces been indepedantly checked (I think many of them have)?

**Comment by rajadain** [comment]
The only difference between `0.3.0` and `0.3.2` is the PR mentioned above, which has been tested. https://github.com/WikiWatershed/mmw-geoprocessing/compare/0.3.0...0.3.2

**Comment by jamesmcclain** [comment]
Okay, thanks.

**Comment by jamesmcclain** [comment]
+1 Since the actual new functionality that the new geoprocessing code brings has already been tested, all I did was make sure that I could provision the `worker` and use the site as normal, which I could.

**Comment by rajadain** [comment]
Since this release is already out there, we must target `develop` instead. Closing this in favor of #1035.

**Pull request closed without merging**
