### PR TITLE
Update animal display names for analysis results

### PR DESCRIPTION
**Pull request by kellyi**
This PR updates the animal display names for the frontend only to match the names specified in #1494:

```
Beef Cows --> Cows, Beef
Broilers --> Chickens, Broilers
Dairy Cows --> Cows, Dairy
Hogs/Swine --> Pigs/Hogs/Swine
Horses
Layers --> Chickens, Layers
Sheep
Turkeys
```
screen shot 2016-09-28 at 2 07 54 pm

The changes will only affect the frontend; the MapShed GMS files will still have the prior names set in `gwlfe_settings.py`. To make the change from the frontend, I replaced the imported values from `gwlfe_settings` used for the `animal_population` method with a set of hard coded `ANIMAL_DISPLAY_NAMES` representing the values above.

**Testing**
- get this branch, `vagrant up`, then visit `localhost:8000` and open the browser console.
- pick an area of interest to analyze, then check the "Animals" tab and verify that the animals are named as above.

Connects #1494

### CODE REVIEW

**Comment by jtarricone** [comment]
+1 Tested

**Comment by mmcfarland** [comment]
@ajrobbins was this request meant to be included in the upcoming release?

**Comment by kellyi** [comment]
HM. I retargeted this to the release branch and it looks like it's pulling in a few prior commits from the self-intersecting shapes thing. I *think* we may have discussed including that in the release, too, but it wasn't pulled in until now.

@ajrobbins @mmcfarland should we keep those for the release or should I open a new version of this with just the single animal display names change?

**Comment by kellyi** [comment]
(I think I'll probably need to rebase this to drop the merge commit either way.)

**Comment by kellyi** [comment]
Cherry picked the single commit for this PR onto a branch made off of `release/1.15.0`.

**Pull request merged**
