### PR TITLE
Add popup for modifications.

### PR DESCRIPTION
**Pull request by caseypt**
* Create view for modifications popup and set as popup content.
* Make modifications clickable and set map mask as unclickable.
* Add modification popup template.

**To Test:**
- Load an existing or create a new model.
- Draw some modifications.
- Click on the modifications to trigger a pop-up.
- Make sure a label appears and that when you click the trash can, the modification is removed, and the count in the scenario toolbar drops.
- Run the tests.

Connects to #252

### CODE REVIEW

**Comment by caseypt** [comment]
Ideally, all of this code would be in `modeling`, but the drawing of the modifications stretches across `modeling` and `core`. I placed it in `core` because it was the simplest way to do it. I tried keeping it all in `modeling`, and assigning the popup content as a attribute on the modification model, but that introduced some problems with serialization, and didn't seem right.

**Comment by rajadain** [comment]
Regarding the delete / trash icon in the popup, it feels a little too small and alone:

image

The icon makes a lot of sense in the tabular compact representation of the Modifications Dropdown, but since we have more room in the popup, what do you think about using a word instead? "Delete", or "Trash" as suggested by the mockup?

**Comment by caseypt** [comment]
@rajadain I'll defer to @ctaylo37 on that. It could use some design help in general.

**Comment by rajadain** [comment]
+1 tested, works as advertised. Deletion works as well. Also works on old projects created long before! Great work.

**Comment by ctaylo37** [comment]
@caseypt If you want to merge this in now, I can take a stab at styling tomorrow.

**Comment by mmcfarland** [comment]
+1 Tested.  Nice small footprint.

**Comment by caseypt** [comment]
@ctaylo37 merged.

**Pull request merged**
