### PR TITLE
Django Upgrade

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Upgrades Django to latest long term supported version for security patches. This is the last version of Django to support Python 2.

Connects #3118 
Connects #3105 

### Notes

There are two known issues with the upgrade that were not resolved, and have been extracted into their own cards:

- Upgrade Django Rest Swagger #3124 
- Verbose Logging for 404s #3125 
- Celery `chord_unlock` Loop #3126

The Swagger update is higher priority, since currently our API docs are broken. The verbose logging is a minor annoyance. The Celery Loop is hard to recreate, but could hold up workers in production if happening consistently.

## Testing Instructions

* Check out this branch and destroy and recreate `app` and `worker`.
  - Also destroy and recreate `tiler` because the tiler service doesn't work after the first time #3112.
* Run migrations `manage.sh migrate`.
* Run `debugserver` and `debugcelery`.
  - Also start `debugtiler` to ensure it is working correctly.
* Go to [:8000/](http://localhost:8000/).
* Ensure you are not logged in.
* Draw a shape and proceed to Analyze. Ensure the analysis completes successfully.
* Go to the Monitor tab and search for items in all four catalogs. Ensure they return results correctly. Spot check the detail pages of those results to ensure they work too.
* Go to the Model tab and create a TR-55 project. Ensure it is created correctly.
* Add a new scenario, and add some changes to it.
* Open the Compare View and ensure it works correctly.
* Go back to the home page.
* Sign up for a new account. Ensure you see the email output in the console correctly. Log in with it.
* Search for a location on the map. Ensure you get suggestions. Ensure you can select a suggestion.
* Select a HUC-10 or HUC-8. Proceed to Analyze.
* Go the Model tab and create a MapShed project. Ensure it is created correctly.
* Add a new scenario. Make some changes. Ensure it works correctly.
* Go to the Water Quality tab, and select Subbasin
* Ensure subbasin results come through correctly

## Checklist

- [x] All JavaScript tests pass `./scripts/testem.sh`

### CODE REVIEW

**Comment by caseycesari** [comment]
When running `debugserver` and visiting the http://localhost:8000, I'm see the following. It looks like the same error, but note the URL at the end error is different.

```
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.monitoring.urls' from '/opt/app/apps/monitoring/urls.pyc'> (monitoring:monitoring) ^health-check/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/usr/local/lib/python2.7/dist-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.default.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/default/urls.pyc'> (None:None) ^accounts/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.bigcz.urls' from '/opt/app/apps/bigcz/urls.pyc'> (bigcz:bigcz) ^bigcz/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.geocode.urls' from '/opt/app/apps/geocode/urls.pyc'> (geocode:geocode) ^mmw/geocode/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.modeling.urls' from '/opt/app/apps/modeling/urls.pyc'> (modeling:modeling) ^mmw/modeling/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.export.urls' from '/opt/app/apps/export/urls.pyc'> (export:export) ^export/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.geoprocessing_api.urls' from '/opt/app/apps/geoprocessing_api/urls.pyc'> (geoprocessing_api:geoprocessing_api) ^api/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.water_balance.urls' from '/opt/app/apps/water_balance/urls.pyc'> (water_balance:water_balance) ^micro/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'apps.user.urls' from '/opt/app/apps/user/urls.pyc'> (user:user) ^user/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /version.txt
```

**Comment by rajadain** [comment]
That's covered in #3125

**Comment by caseycesari** [comment]
I don't have all the data loaded yet, but I'm seeing this error when modeling is kicked off and jobs are polled. 

```
Internal Server Error: /api/analyze/climate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 28, in decorator
    view_result = view(request, *args, **kwargs)
  File "/opt/app/apps/geoprocessing_api/views.py", line 1176, in start_analyze_climate
    ], area_of_interest, user, link_error=False)
  File "/opt/app/apps/geoprocessing_api/views.py", line 1323, in start_celery_job
    headers={'Location': reverse('get_job', args=[task_chain.id])}
  File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'get_job' not found. 'get_job' is not a valid view function or pattern name.
```

This happens for all of the modeling components.

image

**Comment by rajadain** [comment]
Wow yeah I'm seeing that too. Not sure why that didn't happen earlier. Fixing it now.

**Comment by rajadain** [comment]
Fixed in ecba1c2.

**Comment by caseycesari** [comment]
Seeing this error when trying to confirm a new account via the email link

image

**Comment by rajadain** [comment]
Registration URL errors should be fixed in 1acd5e3

**Comment by caseycesari** [comment]
When clicking "I'll do this later" on the profile information modal, I got the following error:

```
AttributeError at /user/profile
This QueryDict instance is immutable

Traceback:  

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  495.             response = self.handle_exception(exc)

File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in handle_exception
  455.             self.raise_uncaught_exception(exc)

File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  492.             response = handler(request, *args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py" in handler
  55.             return func(*args, **kwargs)

File "/opt/app/apps/user/views.py" in profile
  114.         data['was_skipped'] = str(data['was_skipped']).lower() == 'true'

File "/usr/local/lib/python2.7/dist-packages/django/http/request.py" in __setitem__
  435.         self._assert_mutable()

File "/usr/local/lib/python2.7/dist-packages/django/http/request.py" in _assert_mutable
  432.             raise AttributeError("This QueryDict instance is immutable")

Exception Type: AttributeError at /user/profile
Exception Value: This QueryDict instance is immutable
```

image

**Comment by rajadain** [comment]
That should be fixed in 1b41bf8.

**Comment by rajadain** [comment]
Thanks for finding all the bugs! Think I'll have @mmcfarland 	take a look next week if he can. Will squash the fixups for now.

**Comment by mmcfarland** [comment]
Getting some 500s from a few Monitor detail related fetches. Used a "sediment" search around Philly to get to this site.

```
    site_code = site_info.find(namespace + "siteCode")
AttributeError: 'NoneType' object has no attribute 'find'
```

Screenshot from 2019-07-23 10:04:48

**Comment by mmcfarland** [comment]
I created a user and activated it successfully. However, trying to log in with that user gives a 

> Forbidden (CSRF token missing or incorrect.): /user/login

When trying to log in. Same result after page refresh.

**Comment by rajadain** [comment]
Ah sorry, but good catch. I added an addition `@csrf_protect` to the login view to make some tests pass in 86eb0db, but as it is interfering with functionality I'm just going to comment those tests out.

**Comment by rajadain** [comment]
The 500s in Monitor are transitive errors from the underlying APIs we're fetching from, and is a known issue.

**Comment by rajadain** [comment]
Removed the commit that added extra CSRF protection, and added one that removes the failing tests 39e7d4c. Login is working correctly on my end, would appreciate confirmation from yours.

**Comment by rajadain** [comment]
Thanks for the thorough reviews!

**Pull request merged**
