### PR TITLE
Update mini-app data.

### PR DESCRIPTION
**Pull request by jamesmcclain**
The `model.csv` table now has many more significant digits.  In order to accommodate this, numbers must be rounded before they can be displayed (because the display only accepts one digit after the decimal point).

**To Test**
   1. `./scripts/bundle.sh --debug --vendor --tests`
   2. `./scripts/manage.py collectstatic`
   3. Play with the mini-app and see if the values look a little more reasonable.

Connects #635

### CODE REVIEW

**Comment by rajadain** [comment]
Cases when a value (such as ET) is 0", the bar chart should reflect that. Currently, even when ET is shown to have 0", the bar chart has some small value:

image

**Comment by mmcfarland** [comment]
Generally, where reasonable, we should be matching the behavior (and results) of the existing app:

http://www.stroudcenter.org/mmw/mini/

**Comment by rajadain** [comment]
Here's the equivalent screenshot from the existing app:

image

While the numbers are different (as discussed in #541), and they don't add up to Precipitation value (as fixed in this PR), there is correspondence between numbers in the illustration and values in the bar chart.

**Comment by jamesmcclain** [comment]
Okay, I have made that change.

Just to point out: there are now more significant digits in the table, but they are not used anywhere in the mini-app!

Also: this does not solve the problem of the totals not summing to the precipitation, because that is impossible (in general).

**Comment by rajadain** [comment]
+1 great work! Tested that the numbers make sense and the bar chart correctly reflects labels.

**Comment by jamesmcclain** [comment]
Thanks for the review.  I think I'll wait until we've had a discussion about how to index the mini-app csv before merging this.

**Comment by mmcfarland** [comment]
Can you elaborate on why we are unable to get the component totals to sum up to the total precipitation?  I was under the impression that the was the original behavior.

**Comment by jamesmcclain** [comment]
I guess formally the answer is something like this:

None of the precipitation values have any significant digits beyond the 1/10 th position.  If `round` rounds a value to the 1/10th position then wanting the sum of the rounded `runoff`, `et`, and `inf` to always sum to the `precipitation` is equivalent to wanting: precip = `round`(precip) = `round`(runoff + et +inf) = `round`(runoff) + `round`(et) + `round`(inf),  which is equivalent to wanting `round` to be a linear function which it isn't (if you graph it, it would be a step function).

So in general, the sum of the rounded values will not equal the sum of the unrounded values.  They might just have to be tweaked by hand (if that is allowed).

**Comment by mmcfarland** [comment]
If that's the case, then we should evaluate the original implementation and see how they handle it.  I believe that app always has matching totals, and so should this one.

**Comment by rajadain** [comment]
The original app doesn't always have matching totals, as can be seen in this screenshot:

image

2.0" of precipitation is broken down into 0" of evapotranspiration, 0.4" of runoff, and 1.5" of infiltration, which totals to 1.9" instead of 2.0".

**Comment by jamesmcclain** [comment]
Another issue that we have is the infiltration decreasing as the precipitation goes from 2" to the next increment above that on built types such as *high intensity residential* with soil type C or D.  That is caused by the runoff jumping upward as we cross from using the Pitt SSH model at 2" and below to the regular TR-55 calculation at greater than 2".

**Comment by rajadain** [comment]
+1, numbers work well and app behaves as expected.

I think this hash will cause problems in the future:

```javascript
    landMap: {
        'urban_grass': ['turfGrass'],
        'tall_grass_prairie': ['tallGrass'],
        'li_residential': ['lir'],
        'hi_residential': ['hir'],
        'commercial': ['commercial'],
        'desert': ['desert'],
        'deciduous_forest': ['forest'],
        'chaparral': ['chaparral'],
        'grassland': ['grassland'],
        'pasture': ['pasture'],
        'short_grass_prairie': ['shortGrass'],
        'row_crop': ['rowCrops']
    },
```

Before, we were translating from numeric NLCD encoding to alphabetic labels, used in CSS and JavaScript, so it was okay. Now we're converting one alphabetic labeling to another, which adds more noise than signal. This will get worse when we start to actually process the TR-55 results in the back end, since we send the JavaScript style labeling in our API calls which will have to be translated back to Python style labeling there before processing.

Instead of this dual reversal, we should either switch the styling in the front-end to use Pythonic labels, or the labeling in the back-end to use JavaScripty labels. I think that changing the back-end would be easier, since the front-end labels are spread across the app in multiple places. However, we have made a policy decision in #237 to prefer Pythonic labeling in the front-end as well, so I think that would be a a more stylistically fitting choice.

I don't think this work should be done as part of this PR. I'm going to create a new issue for this.

**Pull request merged**
