### PR TITLE
Compare view back button

### PR DESCRIPTION
**Pull request by jamesmcclain**
This patch does two things:

   * **Allow use of back and forward buttons.**  This attempts to fix a bug that prevents navigation form the modeling page, to the analyze page, then back to the modeling page via the browser back and forward buttons.
   * **Add back button to compare view.**  (Of course, this will  not be the final place or appearance for this button.)

screenshot from 2015-09-29 14 03 28
 
Connects #724
Connects #725

**To Test**
   * Navigate to the compare view.  Notice that there is now a left-arrow at the bottom-left of the page.  Pressing it should send you back to the modeling page.  It should also work if you go directly to the compare view without going through the modeling page.
   * Navigate around the site using the browser arrow buttons.  In particular, try moving between the analyze view and the modeling page view the browser arrow buttons.

### CODE REVIEW

**Comment by jamesmcclain** [comment]
@caseypt I had originally assigned you since you created the two cards, but @rajadain requested to review.  Hope that is okay.

**Comment by caseypt** [comment]
Cool with me.

**Comment by jamesmcclain** [comment]
Thanks, I probably should have asked first.

**Comment by caseypt** [comment]
One quick comment though: It would be helpful to provide, in the commit message a synopsis of the problem that was causing the app to break when using the browser buttons.

**Comment by rajadain** [comment]
Oh just saw this thread. Sorry, thought this issue was still unassigned. I'd already started taking a look, will continue.

**Comment by jamesmcclain** [comment]
I just realized that the UI back button does not currently work when you go directly to the compare view.  I will fix that and update the commit message at the same time.

**Comment by rajadain** [comment]
+1 very smooth. Tried:

 * Going back and forth between Analyze and Model, Model and Compare, and all the way from Analyze to Compare
 * Tried navigating via browser buttons and UI buttons
 * Tried landing on the Compare page directly and then hitting the back UI button
 * When returning to the Model view, the last activated scenario is selected, which is great

I feel the button placement, although a little odd, is good enough for now, and uses meaningful color conventions. Sounds like we're going to get a design update pretty soon, so it's good to have the functionality in there ready to go.

**Comment by rajadain** [comment]
Perhaps @caseypt could have a look anyway and provide input on whether this satisfies his original vision.

**Comment by jamesmcclain** [comment]
Thanks for looking, much appreciated!

**Comment by caseypt** [comment]
+1. Nice fix. Tested.

**Comment by jamesmcclain** [comment]
Thanks, I'll merge into develop.

**Pull request merged**
