### PR TITLE
Set current conditions scenario as active

### PR DESCRIPTION
**Pull request by caseypt**
* Fixes an issue where no scenario was set as active when
creating a new project.

### CODE REVIEW

**Comment by kdeloach** [comment]
We should also consider removing this code if it no longer works https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/models.js#L44

**Comment by caseypt** [comment]
@kdeloach That code works when loading an existing project.

**Comment by kdeloach** [comment]
Ah, thanks. Haven't tested creating new projects yet.

**Comment by caseypt** [comment]
Closing this. Fixed in #245

**Pull request closed without merging**
