### PR TITLE
Upgrade Windshaft

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Upgrades the Windshaft tiler.

Connects #3091 
Connects #3082 

### Demo

image

### Notes
<details>
<summary>

~Currently getting the following error in the "Install Windshaft JavaScript Dependencies" step:~ fixed in 8c5d49a8.

</summary>

```json
{
    "changed": true,
    "cmd": [
        "npm",
        "install",
        "--unsafe-perm"
    ],
    "delta": "0:01:04.762965",
    "end": "2019-06-18 15:55:30.183979",
    "msg": "non-zero return code",
    "rc": 254,
    "start": "2019-06-18 15:54:25.421014",
    "stderr": "npm WARN deprecated queue-async@1.1.0: renamed to d3-queue\nnpm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead\nnpm WARN deprecated husl@6.0.6: Project renamed to HSLuv\nnpm WARN mmw_tiler@1.0.0 No description\nnpm WARN mmw_tiler@1.0.0 No repository field.\n\nnpm ERR! path /opt/tiler/node_modules/gdal/node_modules/rc/node_modules/minimist/package.json.2871486687\nnpm ERR! code ENOENT\nnpm ERR! errno -2\nnpm ERR! syscall open\nnpm ERR! enoent ENOENT: no such file or directory, open '/opt/tiler/node_modules/gdal/node_modules/rc/node_modules/minimist/package.json.2871486687'\nnpm ERR! enoent This is related to npm not being able to find a file.\nnpm ERR! enoent \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/vagrant/.npm/_logs/2019-06-18T15_55_30_167Z-debug.log",
    "stderr_lines": [
        "npm WARN deprecated queue-async@1.1.0: renamed to d3-queue",
        "npm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead",
        "npm WARN deprecated husl@6.0.6: Project renamed to HSLuv",
        "npm WARN mmw_tiler@1.0.0 No description",
        "npm WARN mmw_tiler@1.0.0 No repository field.",
        "",
        "npm ERR! path /opt/tiler/node_modules/gdal/node_modules/rc/node_modules/minimist/package.json.2871486687",
        "npm ERR! code ENOENT",
        "npm ERR! errno -2",
        "npm ERR! syscall open",
        "npm ERR! enoent ENOENT: no such file or directory, open '/opt/tiler/node_modules/gdal/node_modules/rc/node_modules/minimist/package.json.2871486687'",
        "npm ERR! enoent This is related to npm not being able to find a file.",
        "npm ERR! enoent ",
        "",
        "npm ERR! A complete log of this run can be found in:",
        "npm ERR!     /home/vagrant/.npm/_logs/2019-06-18T15_55_30_167Z-debug.log"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

</details>

Rollbar and S3 Caching will be tested once this is on staging.

## Testing Instructions

* Delete the `src/tiler/node_modules` directory in your host
* Check out this branch, destroy the `tiler` and reprovision it
* Ensure you have various stream / boundary datasets installed:

    ```bash
    $ vagrant ssh app -c 'cd /vagrant && ./scripts/aws/setupdb.sh -b -d -s -c -p -q -m'
    ```

* Go to [:8000/](http://localhost:8000/) and turn on each layer in the layer selector
  - [x] Ensure all tiler layers work
* Choose "Select Boundary" as the draw tool, and pick HUC-8 as the boundary type
* Hover around an area which is homogenous, i.e. has the same boundary value for entire tiles
* Search away from that area to another homogenous area, i.e. has a different, but same boundary value for entire tiles
  - [x] Ensure the hover value is of the correct boundary, and not a stale value

### CODE REVIEW

**Comment by hectcastro** [comment]
This PR can now be updated to target `develop` vs. `feature/hmc/ubuntu-16.04`.

**Comment by mmcfarland** [comment]
Resolved the above by re-provisioning tiler. There were indications that the error was typical of corrupted `node_modules` directory.  I'm going to retrace some steps to see if I can get it to that state again.

**Comment by rajadain** [comment]
Probably should've included a note in the testing instructions to make sure your host's `node_modules` has been blown away, since now the guest mounts it from an internal cache.

**Comment by rajadain** [comment]
> The TN/TSS/TP DRB streams are just a fraction thicker than on the main site, but I can't find a change to the line width and is too subtle to notice.

The line widths are all multiples of `@zoomBase`:

https://github.com/WikiWatershed/model-my-watershed/blob/e70fef2ce907193a853d6f6f2358706a625ffbb8/src/tiler/styles.mss#L195-L208

which was previously defined as `0.5`:

https://github.com/WikiWatershed/model-my-watershed/blob/e70fef2ce907193a853d6f6f2358706a625ffbb8/src/tiler/styles.mss#L134

In my testing the upgraded version was rendering thinner lines, so I upped it to `0.6`:

https://github.com/WikiWatershed/model-my-watershed/blob/834bf15861a24eaed16c84ee4a42a0c408ee889f/src/tiler/styles/_variables.mss#L1

Feel free to play around with that value and suggest a better one.

**Comment by mmcfarland** [comment]
> Feel free to play around with that value and suggest a better one.

I think it's completely within tolerance given all the rendering upgrades that happened.

**Comment by rajadain** [comment]
Thanks for the thorough review and all the support! Merging this now.

**Pull request merged**
