### PR TITLE
Fix broken log configuration for geoprocessing service

### PR DESCRIPTION
**Pull request by hectcastro**
## Overview

The log routing configuration for the geoprocessing service via Beaver was in a broken state, which was breaking all of the Beaver managed log collection for the application as a whole. This change fixes the geoprocessing configuration, which in turn enables all centralized logging again (Nginx, application, tiler, Celery, Docker, etc.).

### Notes

N/A

## Testing Instructions

First, provision the `app`, `tiler`, and `worker` with the changes in this PR:

```bash
$ vagrant provision app tiler worker
```

Afterwards, ensure that the `services` virtual machine is up-and-running so that you can navigate to http://localhost:5601/. From there, filter messages by `type: geoprocessing` and ensure that there is at least one entry. Also, ensure that logs of other types are also making it into Kibana (e.g., Nginx).

### CODE REVIEW

**Comment by rajadain** [comment]
When I go to http://localhost:5601/, I'm greeted with this message:

image

Should I just go with the defaults or am I missing some configuration elsewhere?

**Comment by hectcastro** [comment]
Ah, I forgot about that step. The options you have set look good. First, click `Create` then when it takes you to the following page, just click `Discover` at the top-left to see the logs.

**Comment by rajadain** [comment]
I checked this out, reprovisioned `app` and `worker`, and recreated `tiler` (because of provisioning issues). Now, I see the following under `type` and `_type`:

image

I ran a TR-55 and MapShed job successfully, but searching for `type: geoprocessing` and `_type: geoprocessing` both result nothing:

image

image

If I search for just geoprocessing, I get these results:

image

Not sure if this is good enough, or if I'm doing something wrong.

**Comment by hectcastro** [comment]
Yeah, this is good enough. The syntax for faceting on a field is something else. Just the presence of the other services on the left signals that it is working.

**Pull request merged**
