### PR TITLE
Add TDX Streamlines Subset Visual Layer

### LINKED ISSUE #3623: AWS 2-5: Evaluate Vector Tiles for Global Watersheds
- [x] Pull sample data from NGA around the Philadelphia area https://earth-info.nga.mil/
- [x] Convert gpkg into json
    ```console
    ogr2ogr -f GeoJSON output.json input.gpkg
    ```
- [x] Convert json into mbtiles
    ```console
    tippecanoe -o output.mbtiles --layer="mylayer" output.json
    ```
- [x] Convert mbtiles into vector tiles
    ```console
    mb-util output.mbtiles ./tiles
    ```
- [x] Upload the tiles to the AWS bucket that hosts other tiles for MMW
- [x] Add VectorGrid plugin to Leaflet
- [x] Add the tile layer as a test

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

This PR adds a demo layer for a TDX Streamlines subset for the US East Coast. The data was pulled from NGA and ingested into vector tiles, as detailed in #3623. These were uploaded to the `tiles.us-east-1.azavea.com` bucket in the `azavea-datahub` account, which also host other static tiles used in MMW.

Since we use an old version of Leaflet in this project, we had to use [Leaflet.MapboxVectorTile](https://github.com/SpatialServer/Leaflet.MapboxVectorTile) instead of [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid). Furthermore, I had to [fork the project](https://github.com/rajadain/Leaflet.MapboxVectorTile) to [make it compatible with our import method](https://github.com/rajadain/Leaflet.MapboxVectorTile/commit/842921d6b93cc1d78960aabbdb13a96ab63b0bc3). The resulting file has now been added directly as a shim, so we don't need to maintain my fork going forward. It is there only for historical purposes.

The layer added here is just for demo purposes. We need to improve styling, stitching, and overzooming before this can hit production.

Closes #3623 

### Demo

https://github.com/WikiWatershed/model-my-watershed/assets/1430060/5f8b5b9e-60ae-4324-aa76-851bdf501066

## Testing Instructions

* Check out this branch
* Run `./scripts/bundle.sh --vendor`
* Go to http://localhost:8000/
* Pick the TDX streams in the layer selector
  - [ ] Ensure you see them load correctly
  - [ ] Ensure they are performant and load quickly

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@rajadain, that exciting to see that video showing how quickly the streams render using this vector tiling approach. Does this result mean that you won't need to use simplified geometries?
cc: @kieranbartels  & @ptomasula

**Comment by rajadain** [comment]
This is the script I used to ingest the tiles: https://github.com/azavea/iow-boundary-tool/commit/a2f157a80a4beac2b0ce213da2dd7b0231a0d68b#diff-2c0b758c29b8d78fc09579aa491396f1dbc124a9da1ab31e42f76bd21dc90141. There was some simplification at lower zoom levels using `--coalesce-densest-as-needed`. Ideally we'd have far fewer streams in the lower zoom levels, styled using stream order as proposed in #3625 (thanks for the clarifications there!).

The plan in #3625 is to style the tiles on the client side / front-end. But if there's a way to actually reduce those extraneous features from lower zoom levels in the tile creation process itself (using some advanced https://github.com/mapbox/tippecanoe facility for example), that kind of simplification could have an impact on our S3 costs.

**Comment by rajadain** [comment]
Added two commits based on work done for #3625.

**Review by rachelekm — APPROVED** [review]
Looks great and very performant! Confirming this works for both tileset options 
Screenshot 2024-06-20 at 10 44 42 AM

**Comment by rajadain** [comment]
Thanks for reviewing!

**Pull request merged**
