### PR TITLE
BiG-CZ Map Hover Improvements

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Improves map hover interactions on the search page in two ways:

 * When not hovering on anything, the map resets to the original state, instead of being stuck on the last hovered item
 * When hovering on an item that is larger than the map's bounds, we show a gold border around the map without obscuring the items, making for a less distracting experience

Connects #2089 
Connects #2090 

## Testing Instructions

 * Check out this branch and `bundle`
 * Go to [:8000/?bigcz](http://localhost:8000/?bigcz)
 * Select an area of interest and search for something
 * Ensure items in the CINERGI tab that are too big to show cause the gold highlight
 * Ensure items fully contained within the map are highlighted as before
 * Ensure items partially contained within the map are highlighted as before
 * Ensure the Hydroshare tab, which has no geometries, works as before
 * Ensure the WDC tab, which has point geometries, supports the new "unhighlight on mouseout" behavior

### CODE REVIEW

**Comment by ajrobbins** [comment]
Is the gold border the same shade as the border of the squares within the viewport? It looks a little brighter. Not sure if that was intentional.

**Comment by rajadain** [comment]
> Is the gold border the same shade ... ?

Yes it is. [Active Element Styling](https://github.com/WikiWatershed/model-my-watershed/blob/3a1193bf6e72f457bbd1b895e27089290d979f86/src/mmw/js/src/core/views.js#L37-L45) vs [Map Element Styling](https://github.com/WikiWatershed/model-my-watershed/blob/03110bc341708c3aa68c843e7437340723ec2c42/src/mmw/sass/base/_map.scss#L33-L39) (notice the color `gold` specified in both).

Unfortunately, since GIF files are limited to 256 colors (8-bit), while our screens run 24- or 32-bit color schemes, the screen capture is lossy and the resulting colors not accurate. When viewing the app in the browser it is easier to see that the border colors are identical.

The fill color of a selected shape is a little darker than the border because it has an opacity of `0.2` or 20%, but the border of both selected shape and map outline are the same colors.

**Comment by arottersman** [comment]
Taking a look now!

**Comment by jfrankl** [comment]
This looks great to me. Nice work @rajadain.

**Comment by rajadain** [comment]
What version of Firefox are you using? I tested the latest v54 on both Mac and Windows and it is working correctly. In fact, the demo GIF is of Firefox on Mac.

**Comment by rajadain** [comment]
My GIF is a little sped up (150%), and my Firefox definitely isn't as slow as yours, but nevertheless I have noticed that the hover operations feel laggy. I'm going to make a card for this. In the interim, let's see if someone else can test on their Firefox.

**Comment by kellyi** [comment]
I took a look at this branch served from @rajadain's machine and saw the outlines properly on my local FF:

screen shot 2017-08-01 at 1 45 54 pm

**Comment by rajadain** [comment]
Thanks. I'm merging this. We're tracking hover performance in #2111

**Pull request merged**
