### PR TITLE
Pad AOI name in analyze tab

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

This PR makes some adjustments to the Analyze tab to enable showing longer AOI names while keeping the scroll behavior intact. To fix it, we drop the 54px fixed height from the header, make some other adjustments to keep it rendering correctly, add some padding to the download csv button at the bottom to ensure it stays visible on scrolling even when the height of the header changes.

Connects #1897

### Demo

screen shot 2017-07-10 at 3 43 36 pm

### Notes

Currently the longest HUC boundary name in the db is 79 char:

```
Little North Fork South Fork Coeur d'Alene River-South Fork Coeur d'Alene River
```

The longest school district is 72 char:

```
Beaufort County School District within Beaufort Marine Corps Air Station
```

Due to some quirks with how the results column's set up the download button will start getting cut off if the title's 160-240+ char long, but since we know the longest current name is just 79, it seems like it makes sense not to adjust the CSS much otherwise

## Testing Instructions

* get branch, then `bundle`, and repeat the following steps in Chrome, FF, Safari, and IE11:
* adjust `aoiHeader.html` to use the 79 char HUC boundary name above as a hard coded name in place of `{{ place }}`, then run analyze and verify that the title no longer overlaps the tab buttons and that the soil and land tabs are fully scrollable & that the download data button's not hidden beneath a div
* model the AOI, then click the analyze tab again and verify that the land and soil tabs are also still fully scrollable

### CODE REVIEW

**Comment by arottersman** [comment]
Working perfectly so far except this:
screen shot 2017-07-10 at 5 44 47 pm

**Comment by kellyi** [comment]
Rebased this on `develop` and pushed ae3cdf6 which fixes the grey block background for "Calculating results..."

**Comment by kellyi** [comment]
Found another place where we need to set the background color explicitly now:

screen shot 2017-07-11 at 4 51 39 pm

d91d840 handles that

**Comment by rajadain** [comment]
@azavea-bot rebuild

**Comment by kellyi** [comment]
Thanks! Going to merge this one.

**Pull request merged**
