### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by caseycesari**
Add note about how to run JS linter

## Testing Instructions

- Verify that this is the correct command.

### CODE REVIEW

**Comment by rajadain** [comment]
Consider adding a mention to [`check.sh`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/scripts/check.sh) in the [Python section](https://github.com/WikiWatershed/model-my-watershed#python) as well.

**Comment by kellyi** [comment]
Would it be worth adding a `lint.sh` script that just called both of these?

**Comment by rajadain** [comment]
I would be up for renaming `check.sh` to `lint.sh` and adding JavaScript linting to it.

**Comment by kellyi** [comment]
Since this is still open: I noticed that the `test.sh` script has a command in it to run the linter as part of the tests, but the line's commented out:

https://github.com/WikiWatershed/model-my-watershed/blob/develop/scripts/test.sh#L18

Not sure why that was commented out in the first place, but if it wouldn't screw anything up I'd be in favor of un-commenting the line so that `test.sh` would do the linting too.

**Comment by caseycesari** [comment]
Going to merge this in, but the other suggestions are worthwhile.

**Pull request merged**
