### PR TITLE
Remove sbo-selenium. 

### PR DESCRIPTION
**Pull request by jamesmcclain**
All occurrences of the string sbo-selenium have been removed.  The tests
continue to run.

### CODE REVIEW

**Comment by mmcfarland** [comment]
+1 Tests pass.

@hectcastro - don't know if you needed to do anything after this was removed, or if you were just hoping it'd get resolved.

**Comment by jamesmcclain** [comment]
I'll wait for Hector's response.

**Comment by hectcastro** [comment]
Looks good to me. It will probably remain installed on the Jenkins machines until we destroy them, but I don't see reason why we need to do that right now. Maybe we can destroy them at the end of the day so that it doesn't slow everyone down on the next build.

**Comment by hectcastro** [comment]
Connects #193

**Comment by jamesmcclain** [comment]
Okay, sounds good.  I will go ahead and merge.

**Pull request merged**
