### PR TITLE
Change /model to /project

### PR DESCRIPTION
**Pull request by caseypt**
* Change the /model route to /project, and update all
references and tests. This route name provides a more
direct mapping the to resource that is being loaded.

**To Test:**
- Navigate to the project page from the root page using the UI controls.
- Save the project.
- Revisit the project using the URL.
- Run the tests.

Connects to #365

### CODE REVIEW

**Comment by rajadain** [comment]
+1 tested. All tests work correctly, as does the UI. Created a new project as anonymous user, logged in to save the project, reloaded page to fetch from server, loaded an older project which had been saved previously: everything works.

There are still some remaining references, more conceptual than programmatic, such as `ModelPackage`, the `modeling` folder, and the `/api/modeling` API route. The latter two aren't as egregious, and I suppose that we should use `ModelPackage` if it is consistent with TR-55 naming conventions, however if we could update that we might get around names such as `ModelPackageModel`.

Given that we are in pre-Beta, I suppose it is okay to release a breaking URL change. Do we need to have redirects from the old routes for any outside users at this point? /cc @mmcfarland

**Comment by mmcfarland** [comment]
@rajadain I considered it, but instead I'm just going to send out work the previously shared project urls won't work (but can be edited).  Nobody is using this for anything real yet.

**Comment by rajadain** [comment]
Great. In this case no more work _needs_ to be done, and my comments above are just _nice-to-have_.

**Comment by caseypt** [comment]
Thanks @rajadain.

In regards to the remaining references, I left them as is because I felt that what the user is largely doing on that page is still modeling, and that the app name should be closer tied to the functionality rather than the route. 

Specifically regarding `ModelPackage`, I would more be in favor of changing our model and collection naming pattern to use singular nouns for models, and plural nouns for collections, rather than appending `Model` or `Collection`. For example, `Scenario` would be a single scenario models, but `Scenarios` would be a collection of scenarios. `ModelPackage` would just be `ModelPackage` then, which I think best describes what that Backbone model represents.

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Comment by caseypt** [comment]
@azavea-bot rebuild

**Comment by kdeloach** [comment]
RE: Removing "Model" suffix. Sounds good.

**Pull request merged**
