### PR TITLE
Fix IE11 Analyze/Model Views

### PR DESCRIPTION
**Pull request by arottersman**
## Overview

The analyze and model sidebars were blank in IE11, because of [this change to the bootstrap stylesheets](https://github.com/WikiWatershed/model-my-watershed/commit/a100f08183d2b7083455013dd8fd83204305317d#diff-4e8e01e9df294745f58db61a059a2a4fR225). This PR reverts the change, and fixes the model toolbar styling which broke without it. 

Connects #1886 

### Demo

_Analyze no longer blank on ie11_
screen shot 2017-05-19 at 1 41 15 pm

_put this thing on the right so it doesn't overlap with sidebar_
screen shot 2017-05-19 at 1 48 49 pm

_put everything on the right like they are in wireframes_
screen shot 2017-05-19 at 1 41 26 pm

_make sure elements don't wrap; while  #1914 is open_
screen shot 2017-05-19 at 1 11 13 pm

## Notes
-  #1867 will handle actual control styling

## Testing Instructions

 * On all major browsers, test both model stages in their "Current Conditions" view and "Scenario" view
     - Confirm all dropdowns, popovers, and tooltips are styled correctly

### CODE REVIEW

**Comment by ajrobbins** [comment]
Just a note that putting "everything" on the right including layer picker leads to https://github.com/WikiWatershed/model-my-watershed/issues/1916 /cc @jfrankl

**Comment by kellyi** [comment]
About to take a look at this!

**Comment by kellyi** [comment]
Possibly for another issue but the MapShed conservation practices selector doesn't scroll on IE11:

screen shot 2017-05-23 at 12 57 17 pm

**Comment by kellyi** [comment]
Scenario name for MapShed's also not showing up in IE11:

screen shot 2017-05-23 at 1 00 15 pm

**Comment by kellyi** [comment]
Does show up for TR-55 though:
screen shot 2017-05-23 at 1 01 05 pm

**Comment by kellyi** [comment]
Not sure whether this was intended or should be spun off to another card but the TR-55 Modifications tab takes up the full screen width in IE11:
screen shot 2017-05-23 at 1 02 25 pm

**Comment by kellyi** [comment]
For comparison, here's that tab in Chrome:
screen shot 2017-05-23 at 1 03 44 pm

**Comment by arottersman** [comment]
- re: scrolling thumb select; I made #1910 to address...it's a pre-existing condition
- re: modifications taking up whole screen + no scenario name in ie11; I'll push a fixup to address! That was most definitely me.

**Comment by kellyi** [comment]
Some of the TR-55 conservation practice text gets cut off in Firefox:

screen shot 2017-05-23 at 1 10 21 pm

**Comment by kellyi** [comment]
Aside from the quirks mentioned above this seems to be working well! I was able to use the models in Chrome, Safari, Firefox, and IE11.

If this one's easy to fix as part of this, might be worth adding a fixup for it too:

> Scenario name for MapShed's also not showing up in IE11:

**Comment by arottersman** [comment]
re: cutoff text in FF; I snuck that one at some point onto #1897. It's unfortunately on staging

**Comment by arottersman** [comment]
I was able to fix the mod dropdown taking up the whole width, but couldn't reproduce the missing scenario name:

screen shot 2017-05-23 at 4 25 26 pm

**Comment by kellyi** [comment]
Trying this out again; I think I'm able to reliably reproduce the missing scenario name like this in IE11:

1. run MapShed on an AOI
2. when those results return, click to "Add Changes..."
3. select and apply a conservation practice
4. click on the scenarios tab to go back to "Current Conditions"

At that point it looks like the scenario name disappears and the dropdown won't really work. I checked this on Chrome/macOS and it didn't seem to have the same issue btw.

**Comment by kellyi** [comment]
TR-55 modifications tab looks correct now, btw. I think the missing scenario thing in that one situation is the only other breaking IE11 issue I encountered.

If it's not too difficult to address, might be good to handle it as part of this work; if it's super involved to fix, we could spin it off into another issue.

**Comment by arottersman** [comment]
Oh, that's probably related to #1911. There's an `Object.assign` in there that breaks the whole thing after adding a conservation practice.

**Comment by kellyi** [comment]
> There's an Object.assign in there that breaks the whole thing after adding a conservation practice.

Got it. Ok, this is otherwise good to go!

**Comment by arottersman** [comment]
Thanks!

**Pull request merged**
