### PR TITLE
Feature/lol/celery versions

### PR DESCRIPTION
**Pull request by lliss**
Connects #316

Provides a way to prevent stacks (green/blue) from running jobs provided by an alternately colored stack. Use black as a default value for development and as a reasonable default if something fails to properly provision.

### CODE REVIEW

**Comment by mmcfarland** [comment]
Is `Black` used just for environments which are not associated with a stack color?

**Comment by lliss** [comment]
Correct. As a default for dev or errors.

**Comment by lliss** [comment]
@azaveabot rebuild

**Comment by mmcfarland** [comment]
Looks good to me.

**Comment by mmcfarland** [comment]
You'll want to add 
Connects #316

**Pull request merged**
