### PR TITLE
ITSI Improved Session Resumption

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Previously there were two issues with loading existing projects in ITSI Embed mode:

 1. Loading took too long, a user could begin interacting with the app before loading completed, and could interfere with the saved state.
 2. It was not possible to save and load a project that hadn't reached the modeling stage. We were not saving a project with only an AoI at the draw stage, and there was no way to resume from this stage.

This PR addresses both concerns by doing the following:

 1. Switches to Backbone routing instead of full page refresh which is orders of magnitude faster and does not let the user interact with the app before project is loaded.
 2. Adds saving and loading mechanism to the draw stage.

### Prepare an Activity for Testing

 1. Checkout the branch and run the bundle `./scripts/bundle.sh --debug`
 2. Run [ngrok](https://ngrok.com/) `ngrok http 8000`
 3. Log on to [ITSI](https://learn.staging.concord.org) as `mmwterence` and edit the [**MMW Example 6abdbbf1**](https://learn.staging.concord.org/eresources/506/matedit?iFrame=true) activity
 4. Update the Activity Name to have the URL of your ngrok instance for identification purposes and click "Save":  
  image
 5. Edit the first page of the activity:  
  image
 6. Edit the embedded app:  
  image
 7. Update the name and URL to match your ngrok instance:  
  image
 8. Click "Save"

### Test the PR

 1. Log in as `tstudent2`, and open the activity.
 2. Draw an AoI.
 3. Close the tab. Open the activity again. It should be initialized to the draw view with the correct AoI.
 4. Proceed to Analyze. Proceed to Model.
 5. Close the tab. Open the activity again. It should be initialized to the project view.

Connects #668

### CODE REVIEW

**Comment by rajadain** [comment]
Please hold off on reviewing this until after today's demo.

**Comment by rajadain** [comment]
Okay this is ready for review now. Embed URL https://e0ebfe64.ngrok.io/?itsi_embed=true

**Comment by lewfish** [comment]
+1, tested.

**Comment by mmcfarland** [comment]
Also tested in demo yesterday, worked well and everyone was pleased with the progress/result.

**Comment by rajadain** [comment]
Encapsulated ITSI notification in `updateItsiFromEmbedMode`, and now nullify `App.itsi` if it exists from `testUtils.resetApp`, according to comments on https://github.com/rajadain/model-my-watershed/commit/e3b81d2469b8dfc3118bf30a4e675aaa1b8fcaba. Will merge shortly.

**Pull request merged**
