### PR TITLE
On draw error, keep draw tools enabled

### PR DESCRIPTION
**Pull request by arottersman**
## Overview

When canceling a draw session (pressing ESC or drawing an invalid AoI) the map would end up in a bad state where the draw tool view was still open, but the tool was no longer enabled. Now when we cancel the draw, we re-enable the same draw tool, and don't clear the event listeners. 

Connects #2031 

### Demo

e7zqz4t7mf

## Testing Instructions

 * Try to draw a shape the size of the states
    * Confirm you can try to draw again after you cancel the Too Big AoI Modal
 * Start to draw a shape but before finished it, press the escape key
    * Confirm you can go right back to drawing a shape
 * Press the escape key while using the Select square km tool — confirm it does nothing
 * Confirm canceling the draw tool with the "x", drawing valid AoIs, and selecting boundaryies still work

### CODE REVIEW

**Comment by arottersman** [comment]
I broke a test.

**Comment by arottersman** [comment]
I fixed the test.

**Comment by rajadain** [comment]
Taking a look at this now.

**Comment by arottersman** [comment]
Thanks for testing!

**Pull request merged**
