### PR TITLE
Use NLCD colors for land uses.

### PR DESCRIPTION
**Pull request by jamesmcclain**
The fill color for each has been changed to that which corresponds with its NLCD code.  The stroke colors have been changed to those on the opposite side of the color wheel.

Connects #712

screenshot from 2015-08-31 13 01 05

screenshot from 2015-08-31 13 00 36

### CODE REVIEW

**Comment by rajadain** [comment]
+1, tested on various basemaps, the polygons are easily seen on all.

I see that since they use the same NLCD codes, Turf Grass and Tall Prairie, and Pasture and Short Prairie, share colors:

image

Turf Grass and Tall Prairie still remain easily distinguishable because of their very different patterning. Perhaps we may need some design assistance to develop similar distinguishable patterning for Pasture and Short Prairie.

**Comment by caseypt** [comment]
Consider updating the outline colors, which can be configured here: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/modificationConfig.json

**Comment by rajadain** [comment]
I wonder how it will look once #601 is available. If the modifications are the same colors as the basemap, it might be confusing.

**Comment by mmcfarland** [comment]
@rajadain We're actually going for an effect like that, since applying these tools is essentially a reclassification of use.  If you extend an existing area of agriculture land with more agriculture, they should look reasonable contiguous or at least imply that they are the same value.  We may need to dial down the opacity so the existing use type doesn't bleed through too much.

**Comment by lliss** [comment]
Appearance-wise, I think this looks good. You have my +1

**Comment by jamesmcclain** [comment]
> Consider updating the outline colors, which can be configured here: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/modificationConfig.json

Okay, will-do.

**Comment by mmcfarland** [comment]
:+1:  Looks good.  Can you make an issue to develop a new distinguishing pattern for Pasture/Prairie?  We can tweak the small stuff like opacity once we have the overlays loading.

**Comment by kdeloach** [comment]
+1 Tested

**Pull request merged**
