### PR TITLE
Upgrade jQuery

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Upgrades jQuery to 3.3.1 for security reasons. Also adjusts various deprecated calls in accordance with [the migration guide](https://jquery.com/upgrade-guide/3.0/).

Connects #2613 

### Notes

I expect subtle edge cases to be discovered as side effects of this in the near future.

## Testing Instructions

  * Check out this branch
  * The last commit removes `jquery-migrate`, which logs deprecated features to the console. Do `git checkout HEAD~1` to get a version of this branch that still has it.
  * Run `./scripts/npm.sh install` to get the new jQuery
  * Go to [:8000/](http://localhost:8000/) and verify _the entire app_ with the console open and ensure everything works and there are no deprecation warnings
  * Go to [:8000/?bigcz](http://localhost:8000/?bigcz) and verify _the entire app_ with the console open and ensure everything works and there are no deprecation warnings

### CODE REVIEW

**Comment by arottersman** [comment]
Taking a look now

**Comment by arottersman** [comment]
Some initial regressions; haven't tested integrations with ITSI or hydroshare yet:

## MMW

1. Pagination is broken on the Analyze Water Quality and Point Source tabs. To recreate, analyze the Schuylkill HUC-08 and press the "Next" button on the water quality table

<details>
<summary>pics </summary>
screen shot 2018-02-07 at 2 55 43 pm
screen shot 2018-02-07 at 2 55 24 pm

</details>
</br>

2. Clicking a TR-55 modification doesn't close the thumb select drop down. On staging, selecting a modification under Land Cover or Conservation Practice closes the drop down. On this branch, the drop down remains open. The tool still works however.

-------------
## BiG-CZ

1. Can't select a list pop-up item after using pagination. To recreate, search for water on the CINERGI tab and click the map. Go to the next page on the list popup and attempt to select a list item

<details>
<summary> pic </summary>
screen shot 2018-02-07 at 3 07 23 pm

</details>
</br>

2. Can't close cinergi detail — I'm not 100% sure how to recreate this, but best guess is the pagination again. Page through CINERGI results and then select a detail and try to go back from the detail view.

<details>
<summary>
 I saw this error and was completely stuck there...
</summary>

screen shot 2018-02-07 at 3 08 22 pm

</details>

**Comment by arottersman** [comment]
One additional very minor thing:

The loading message no longer appears on the layer picker's Observable tab
cirts3sgrr

**Comment by arottersman** [comment]
Great work powering through this! It is almost entirely functional. I found one additional regression. Surprisingly hydroshare, ITSI/screenshots are still working just fine. The geocoder, however, has a new bug:

1. Search for something and select an ESRI result
2. Try and search for something again and the loading spinner will go forever. Here's the console error:

screen shot 2018-02-07 at 4 17 13 pm

**Comment by rajadain** [comment]
Taking a look at these issues now.

**Comment by rajadain** [comment]
> Can't close cinergi detail — I'm not 100% sure how to recreate this, but best guess is the pagination again. Page through CINERGI results and then select a detail and try to go back from the detail view.

I was unable to recreate this after fixing the pagination, so hopefully it was just that. All the other ones should be fixed by the above. Great investigation! If you could verify those I'll squash and merge. Thanks!

**Pull request merged**
