### PR TITLE
Add Subbasin Container; Refactor Result Models

### PR DESCRIPTION
**Pull request by arottersman**
## Overview

This PR gets the subbasin view ready to display results in the tables. 

The refactoring and changes are described in the commit messages, but most notably this PR

* moves the gwlfe error off of a scenario and on to result models so that subbasin errors don't muddy the regular model views
* adds mapshed error attributes to the scenario so that we can catch when mapshed fails. Previously mapshed failure would make Gathering Data spin forever. Now there will be a proper error.
* Adds the subbasin model to the GWLFE model collection
* Refactor the subbasin container view to reuse the existing polling state/result view set up
* Add AOI info and blank tabs to the subbasin view 

Connects #2650 

### Demo

xxvv1nc49d

## Notes
* Existing mapshed projects won't be subbasin modelable until #2750 

## Testing Instructions

 * Pull and bundle
* Select a HUC-10 and progress it to subbasin modeling. Confirm you end up on a view with the aoi details and empty tabs once the polling completes.

* Put the browser offline or otherwise cause a failure during the mapshed/Gathering data step. Confirm you see an error

* Briefly test TR-55 and confirm there are no regressions

### CODE REVIEW

**Comment by arottersman** [comment]
I broke a unit test. Will fix momentarily!

**Comment by arottersman** [comment]
This is ready for review now.

**Comment by kellyi** [comment]
Setting this up to review!

**Comment by kellyi** [comment]
Aside from that everything is working. We chatted briefly about this but: the perpetual "gathering data" on `MAPSHED data` failures is how the prior modeling tabs work too.

Seems like it's doable to fix just this subbasin tab to show an error instead of "gathering data" when the `SUBBASIN MAPSHED data` step fails. I can take another look at this when you'd like -- and we should probably make another enhancement card for dealing with the non-subbasin mapshed failures.

**Comment by arottersman** [comment]
Thanks for catching that. The errors weren't working because they populate on the project, not the scenario. The fixup should address both the regular mapshed and subbasin mapshed error cases!

**Comment by kellyi** [comment]
Great -- taking another look at this!

**Comment by kellyi** [comment]
This is working very well! I did notice one case in which the errors are not fully propagated through to the UI, viz.:

If you turn off the network before clicking "View attenuated subbasin results" the network request will fail but the spinner will keep going. Same thing happens with Mapshed. We should handle this in another card though, as it's outside the scope of this one.

**Comment by arottersman** [comment]
Thanks for all your testing, Kelly! Just squashed the fixups and will merge after this builds.

**Pull request merged**
