### PR TITLE
Load school districts

### PR DESCRIPTION
**Pull request by mmcfarland**
Update setup script to load a national school district boundary layer.

A new script option `-f` allows you to load up a single, name layer and not have to reload all boundary data sets to add a new one.  For example, from an app server you could run

`./setupdb.sh -f boundary_school_district.sql.gz`

to add just this new dataset.

The data set was sourced as a shapefile from http://nces.ed.gov/programs/edge/geographicDistrictBoundary.aspx and originally processed into PostGIS with the following settings:

```bash
shp2pgsql -s 4269:4326 -d -g geom -I -W "LATIN1" schooldistrict_sy1314_tl14 public.boundary_school_district
```

##### Testing
From you local app server run either 
* `./setupdb.sh -f boundary_school_district.sql.gz` or `./setupdb.sh -d` to load the new dataset
* Test that the tiles can be generated by requesting http://localhost:4000/district/10/300/387.png

Connects #730 and will be used in #629

### CODE REVIEW

**Comment by caseypt** [comment]
:+1: 

screen shot 2015-08-31 at 5 07 48 pm

**Comment by caseypt** [comment]
Also, thanks for not messing with the app layer settings. I'll add this layer in the PR I'm working on for #629.

**Comment by lliss** [comment]
+1

**Comment by mmcfarland** [comment]
Yeah, I knew you were rearranging the guts of it and didn't want to get involved.

**Pull request merged**
