### PR TITLE
Make RWD work near border of DRB

### PR DESCRIPTION
**Pull request by lewfish**
The DRB perimeter is used on the frontend to decide if a point can have RWD run on it. Previously, we used a simplified version to have a smaller payload, but this excluded some places that are inside the DRB. This PR makes it so the frontend uses a buffered (expanded by 20 miles) and simplified DRB (Delaware River Basin) perimeter to avoid this issue. It also switches to using the full DRB perimeter on the backend to maintain accuracy. 

As part of an effort to make the data wrangling process more repeatable, I've included a script and some instructions on how these new files were generated as part of the source code.

#### Testing
* Run `./scripts/debugserver.sh` and `./scripts/debugcelery.sh`.
* Try running RWD on a point that is clearly inside the DRB (eg. Philly). It should work.
* Try it on a point that is clearly outside the DRB (eg. Pittsburgh). The frontend should immediately reject it.
* Try it on Avon Grove Intermediate School, which was reported in the issue. It should work.
* Try it on a point that is inside the buffered polygon, but outside the true DRB perimeter (eg. Lancaster). It should start RWD, but then server should respond with an error.

Connects #1583

### CODE REVIEW

**Comment by caseypt** [comment]
Just to be clear, da520e5 is unrelated to the DRB issue, right?

**Comment by lewfish** [comment]
> Just to be clear, da520e5 is unrelated to the DRB issue, right?

Right.

**Comment by caseypt** [comment]
This doesn't seem to be problem in the app, but just FYI both of the DRB GeoJSON files are invalid GeoJSON because they do not have a `properties` key.

**Comment by caseypt** [comment]
Consider decreasing the size of the buffer (I'm not sure what the right number is, 2 miles?). Even though the back-end is using the real shape, it seems like we are leaving a lot of room for RWD to pass the initial test, but fail to return results.

Original:
image

Buffer
image

**Comment by lewfish** [comment]
> This doesn't seem to be problem in the app, but just FYI both of the DRB GeoJSON files are invalid GeoJSON because they do not have a properties key.

I'll add that and find a better buffer distance for a snugger fit.

**Comment by lewfish** [comment]
With a 3 mile buffer:

screen shot 2016-11-03 at 11 45 25 am

**Comment by caseypt** [comment]
Cool. That looks good to me.

**Comment by caseypt** [comment]
Tested things out with the new buffer. Looks good.

**Comment by lewfish** [comment]
Thanks for the review.

**Pull request merged**
