### PR TITLE
ITSI Login and Screenshot Issue Fixes

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Fixes login and screenshot issues as described in #950. See commit messages for details.

## Testing Instructions

 1. Login to https://learn.staging.concord.org/ as `tstudent2` and open the MMW Example da76db03 activity.
 2. Start the activity. It should automatically try to log you in, but will not find a corresponding account, and will try to create one for you.
 3. The account name should autopopulate as `tstudent2.itsi`. Change it to `tstudent2`. Try signing up. You should see the "Username already exists" prompt.
 4. Dismiss the modal by clicking outside, or by selecting "Continue as Guest". You should be redirected to the home page and the draw tools should render.
 5. Try and take a screenshot. It should render correctly and not show you an ITSI or MMW login screen.
 6. Try and login. Select "ITSI" in the login box. Sign up as `tstudent2.itsi`. Ensure you can still take screenshots.

Connects #950

### CODE REVIEW

**Comment by rajadain** [comment]
Alright I've re-setup the application to use a new `ngrok` URL running off my local. Ready for testing.

**Comment by mmcfarland** [comment]
I think we should add a label to this screen, which is hard to distinguish from a login screen, that we are creating a MMW account linked to their ITSI Account.  Something along the lines of:

> We need to create a new account for you in Model My Watershed associated with your ITSI username: {{itsi_user}}.  Please pick a display name and sign up below.  You should always log in with the "Log in as ITSI" button.

screenshot from 2015-10-14 09 56 22

**Comment by mmcfarland** [comment]
I'm not seeing the Draw Tools rendered as indicated in step 4 above:
screenshot from 2015-10-14 09 57 12

**Comment by rajadain** [comment]
Okay taking another look. Will delete the `tstudent2.itsi` user to recreate some of this.

**Comment by mmcfarland** [comment]
Guest screenshot works well, as does signup/login screenshot.

**Comment by rajadain** [comment]
The reason the draw tools weren't rendering was because the activity had saved a state for a project that no longer existed (because I'd deleted the user in preparation for this):

image

And that error would break the Backbone controller. I've cleared the ITSI saved state and the draw tools render correctly now.

**Comment by mmcfarland** [comment]
Given that user can manage their projects, is this in error condition that we should make an error for to handle better?

**Comment by mmcfarland** [comment]
Tools are rendering in Guest mode now.

**Comment by rajadain** [comment]
The error condition has now been minimally handled in dfbf4fd5ec1105caa796b4a9b942c7be8a1dafbe, and I've created #953 to make that more robust.

I've also added help text to the ITSI sign up modal. We can't have too much of it, because even one more line will make the user have to scroll to be able to press buttons on the modal:

image

Any feedback on further improving the help text would be welcome.

**Comment by mmcfarland** [comment]
Looks good - I wonder if the "Sign Up with ITSI" button text could be improved.  Something like "Complete signup with ITSI" or "Finish linking account with ITSI" - both are pretty verbose, but "Sign Up With ITSI sounds like a _new_ option (like "Continue as Guest") instead of completing this current action, aka "Done".

**Comment by rajadain** [comment]
Since we're already saying "This will link to your {username} ITSI account", we don't need to repeat "with ITSI" in the button, and can just say something like "Complete Sign Up" or "Finish Linking Accounts". On the other hand, we do have a lot of space in the wide button, and could potentially fit in more.

I also wanted to improve the "Always pick ITSI when logging in" line, which sounds incomplete and not very friendly. I want to say something more like "Just use ITSI when logging in to log in" but that sounds very redundant, verbose and confusing.

Perhaps we could get some design assistance?

**Comment by rajadain** [comment]
Closing in favor of #955.

**Pull request closed without merging**
